### ISSUE TITLE
Wrong database population in Edit Panel

### ISSUE THREAD

**Issue by Gabilehner** [grafana/azure-data-explorer-datasource#10]
When I edit a panel the database selection is automatically populated with the first database in the list and not the one saved previousely.
Then the query shows an error.

**Comment by srclosson** [comment]
@Gabilehner:What version of the azure data explorer datasource plugin are you using? 

I'm not able to reproduce the behavior here...

**Comment by Gabilehner** [comment]
Can you give me some context around this question?

Thanks,
Gabi

**Comment by erikbos** [comment]
Plugin v1.3 has the behaviour as described above: when you go into edit mode of an existing panel the first database gets selected (based on alphabetical order?) and not the one that was saved. 

I haven't used v2.0 that much yet, but it does not appear to have this bug.

**Comment by srclosson** [comment]
Version 2.0 does not exhibit this behaviour. Moving forward, all changes will be made of the 2.0 branch. Suggest upgrading to 2.0 for this fix.
