### ISSUE TITLE
Please add user name as part of request id

### ISSUE THREAD

**Issue by gilkgit** [grafana/azure-data-explorer-datasource#103]
Our ADX cluster is showing some slowdown, we noticed that Grafana is bombarding the cluster with queries.
The thing is that we can't see neither who the offending user is nor the what is the offending dashboard.
It's actually not the first time this happens and we had to shut down Grafana because of this.

Other dashboarding solutions emit dashboard identification to the ClientActivityID field so it's viewable using ".show queries".
I see that you already have a feature request opened for it.

My request is to also add the user id to the ClientActivityID (or to anywhere else that is viewable with .show queries).
Other dashboarding tools we have use the user credentials for authentication to ADX and running queries, so the offending user is displayed in the User field returned from ".show queries".
This is not possible with Grafana as it authenticates with a single app id.

**Comment by erikbos** [comment]
https://github.com/grafana/azure-data-explorer-datasource/issues/166 is similar/related

**Comment by joshhunt** [comment]
This was added and released in 3.3 https://github.com/grafana/azure-data-explorer-datasource/issues/166#issuecomment-761162598
