### ISSUE TITLE
How to add China Mooncake azure data explorer endpoint?

### ISSUE THREAD

**Issue by hundunmuchi** [grafana/azure-data-explorer-datasource#106]
Hi,

Would you please share how to add azure data explorer connection to mooncake environment? I noticed the plugin only worked for  public endpoint. Thanks,

Andy

**Comment by nonokangwei** [comment]
Same request for Azure China ADX support, tried on change the plugin config, it seems still using the global azure AAD which block the plugin connect the instance in Azure China.

**Comment by joshhunt** [comment]
This isnt supported yet. I'll close this issue in favor of https://github.com/grafana/azure-data-explorer-datasource/issues/16
