### ISSUE TITLE
Feature Request - Authenticate to ADX using user credentials instead of a single application credentials 

### ISSUE THREAD

**Issue by gilkgit** [grafana/azure-data-explorer-datasource#107]
We'd prefer if the ADX plugin would not use a single App ID for authenticating to ADX, but instead will propagate user credentials for the query.

For us this will enable a few more scenarios that we now restrict due to  this single app authentication.

It'll also make managing permissions easier since users will automatically be restricted to view panels results according to their permissions over the "raw data".

**Comment by gilkgit** [comment]
this was added in 7.4.0 : 
"Backend plugins: Support Forward OAuth Identity for backend data source plugins"
https://github.com/grafana/grafana/pull/27055.
It might aid in the way to implement this user credentials authentication ask

**Comment by brycefisher** [comment]
This is a great idea! At my org, we have a much easier time provisioning access to Grafana user accounts than Azure AD user principals, so it would be ideal if we could preserve the current implementation when building this feature.

The ability to track some notion of a user from grafana on a per Kusto API call in #166 sort of relates to this as an alternative way to get observability into the user/dashboard/panel which somewhat overlaps with the possible goals behind this feature request.

**Comment by jkrauska** [comment]
Agreed -- maintain user auth instead of broadly granting the service account database access would make this much more fine grained for security concerns.

**Comment by kkerssem** [comment]
Hi, I see some refactoring ongoing in pull request #227 by Erik Sundell. Will this feature be part of that refactoring?
We could really use an oauth forwarding feature in order to implement a row-based authorization policy in ADX.

**Comment by Dammi87** [comment]
I have the exact same issue - We want to implement row-level security per user, but there is no way of knowing which user is viewing the dashboard in Grafana.

This is the result I get straight from ADX
![image](https://user-images.githubusercontent.com/23643258/124604304-5508e000-de5a-11eb-904f-6c18260f1d55.png)

While this is what is shown in Grafana
![image](https://user-images.githubusercontent.com/23643258/124604565-95685e00-de5a-11eb-85c9-2c6ed20ccf1d.png)

We are using AD to login to our Grafana server.
