### ISSUE TITLE
Decimal column support

### ISSUE THREAD

**Issue by blackbaud-brandonstirnaman** [grafana/azure-data-explorer-datasource#116]
Using Grafana 7.1.4 with ADX plugin 3.0.1.. If I run any query against ADX that returns a decimal, I get this error:

![image](https://user-images.githubusercontent.com/13523460/91183246-3d4cc100-e6b9-11ea-82e3-85ddc2612aa4.png)

**Comment by mckn** [comment]
@kylebrandt this might be the same issue as the other scenario? Is the proper type missing in the ADX response.

**Comment by secustor** [comment]
I can confirm this issue with Grafana v7.2.0 and the ADX plugin 3.1.0. 

The reason why this seems not to working, is that there is no decimalConverter function in [table.go](https://github.com/grafana/azure-data-explorer-datasource/blob/master/pkg/azuredx/table.go)

Would you accept a PR for that?

**Comment by mckn** [comment]
@secustor yes! that would be awesome 👍
