### ISSUE TITLE
KQL editor : Ctrl+Backspace doesn't work

### ISSUE THREAD

**Issue by sloutsky** [grafana/azure-data-explorer-datasource#139]
Ctrl+Backspace in embedded Monaco editor doesn't work (should remove a single word).
After Ctrl+Backspace is entered, Ctrl+Arrow doesn't work either (at least until keyboard cursor is not moved)

**Comment by vickyyyyyyy** [comment]
this is now supported in v3.6.0

**Comment by andresmgot** [comment]
Had to revert #276 so reopening this. Take into account the issues reported at #284 when retrying this.

**Comment by andresmgot** [comment]
well, closing this in favor of https://github.com/grafana/azure-data-explorer-datasource/issues/224 since this will be fixed once that is closed.
