### ISSUE TITLE
Support for Alias by for legend

### ISSUE THREAD

**Issue by alexjson** [grafana/azure-data-explorer-datasource#14]
This is how it looks like for influxDb
![image](https://user-images.githubusercontent.com/1343753/61780197-5faf4380-ae02-11e9-942c-3b1b742a6ca6.png)

This is how it looks like on Azure data explorer
![image](https://user-images.githubusercontent.com/1343753/61780256-7fdf0280-ae02-11e9-86df-b72e3f1de65b.png)

Would it be possible to add the Alias By to get the labeling on the legend ? 
Currently the legend for azure data explorer only shows the colors 
![image](https://user-images.githubusercontent.com/1343753/61780530-01cf2b80-ae03-11e9-9642-4ee2697d037a.png)

For influx we have this
![image](https://user-images.githubusercontent.com/1343753/61780619-27f4cb80-ae03-11e9-9c59-ad696c6e303a.png)

**Comment by alexjson** [comment]
nvm, found the correct way of doing it

**Comment by spacentropy** [comment]
I'm sorry, but what is the correct way of doing it? 
We get metric name like this: 
![image](https://user-images.githubusercontent.com/464801/71414422-ed1fe980-2667-11ea-869b-4cb1344c1633.png)
but would prefer to have it as "jpy-delivery"
also "ALIAS BY" field is missing in our version of plugin(2.0)
