### ISSUE TITLE
Error when editing queries with v3.0 or higher: Could not load datasource schema: [object Object]

### ISSUE THREAD

**Issue by L3bannen** [grafana/azure-data-explorer-datasource#144]
With plugin version 3.0 or higher I can't edit queries, instead I get an error.

I connect to the datasource just fine, but when I want do a new query, the field doesn't appear and I get the error 

**Could not load datasource schema: [object Object]**
![grafana_error_datasource](https://user-images.githubusercontent.com/71662978/93801266-062ee880-fc42-11ea-866c-735bf59acb8f.PNG)

I tried using older version of grafana but it doesn't change anything with my problem so it seems to be something that changed since 3.0.

Is there a workaround to this issue? 

My data source is [playfab](https://docs.microsoft.com/en-us/gaming/playfab/features/insights/connectivity/connecting-grafana-to-insights), I have no issues when using [Azure Data Explorer](https://dataexplorer.azure.com/) directly or older versions (2.x.x) of the Azure data explorer datasource. 

I'm sorry if this was already resolved elsewhere, tried to search everywhere but couldn't find anything.

**Comment by mckn** [comment]
Thanks for reporting this. To be able to help you to resolve this I would need some more information from the network tab in your browser. Could you please send me the response on the following request?

<img width="1102" alt="Skärmavbild 2020-09-23 kl  09 38 51" src="https://user-images.githubusercontent.com/172951/93981746-a3903680-fd80-11ea-83b0-39d46b8eb576.png">

**Comment by L3bannen** [comment]
Is this helpful ?

![image](https://user-images.githubusercontent.com/71662978/94012343-f5e54d80-fda8-11ea-81fb-97b5838589ec.png)

**Comment by L3bannen** [comment]
I tried running the same command frome Azure Explorer directly and it does respond with an error as well: 

` Unsupported management command: .show databases schema as json

 clientRequestId: KustoWebV2;40135c71-ff8f-4b62-aeee-980fa3367810`

**Comment by mckn** [comment]
> I tried running the same command from Azure Explorer directly and it does respond with an error as well:
> 
> **Unsupported management command: .show databases schema as json**

Perfect thanks! I will look into this asap.

**Comment by mckn** [comment]
@zivcaspi do you know in what version of ADX this command was added? 

https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/show-schema-database

And do you know what version the playfab is running?

**Comment by L3bannen** [comment]
Hello,

If that can help: the command  **.show databases schema** _does_ work on the version playfab is running. It seems it doesn't like the "as json" part.

Let me know if you want me to try anything.

Cheers

**Comment by mckn** [comment]
Ah, super! That helps a lot. I will try to fix this to the next release. Thanks for the help 🙏

**Comment by sloutsky** [comment]
@L3bannen - can you please elaborate which cluster / data source you are working with? 
All Kusto (ADX) clusters support this command - and if playfab mid-tier/proxy is blocking this command - we can get in touch with them to get it completed.

@mckn : I would _not_ recommend using .show databases schema command, as it has significantly worse performance when it comes to clusters with many databases.

**Comment by L3bannen** [comment]
@sloutsky Here is the cluster URL: https://insights.playfab.com/ 

Playfab is part of Microsoft (and has now been renamed "Azure playfab" https://playfab.com/

Here is the official documentation from Microsoft to connect grafana to playfab: https://docs.microsoft.com/en-us/gaming/playfab/features/insights/connectivity/connecting-grafana-to-insights

I checked this morning and the command .show databases schema as json still doesn't work.

Hope it helps.

**Comment by grilme99** [comment]
Hi,

I am also having trouble with this when using PlayFab like @L3bannen. I am on the <https://insights.rblx.playfab.com> cluster, however. Is there any sort of workaround until this can be fixed?

Thanks!

**Comment by sunker** [comment]
@gabilehner it seems like Playfab is using an old version of ADX. This is not something we can fix or provide a workaround for on our side, right?
