### ISSUE TITLE
Kusto: QueryBuilder: time binning is not added in time-series 

### ISSUE THREAD

**Issue by sloutsky** [grafana/azure-data-explorer-datasource#156]
In the recent release of 3.1.0 - seems that time binning is not added to the query , and limit 10000 appears at the end of the query.
Screenshot attached:

![image](https://user-images.githubusercontent.com/17802887/94360628-71037800-00b7-11eb-815f-10a56376ba80.png)

**Comment by mckn** [comment]
@sloutsky the reason for the missing binning is that you don't have any time column selected in the `Group By` clause. So you need to add one to get the binning.

I know this isn't optimal and we probably should guide the user a bit better in the UI. We have a todo for this in the v3.2.

**Comment by sloutsky** [comment]
Cool, thanks - that's explains it.
