### ISSUE TITLE
No tool tip above icons

### ISSUE THREAD

**Issue by avneraa** [grafana/azure-data-explorer-datasource#157]
When I hover above the icons I don't see tooltips that tell me what they are:

![image](https://user-images.githubusercontent.com/4261958/94361834-ef641800-00bf-11eb-93ab-1eb4ea44f489.png)

**Comment by avneraa** [comment]
It actually show up but after really long time, so it is just not snappy

**Comment by mckn** [comment]
> It actually show up but after really long time, so it is just not snappy

Not sure we can change this since it is the browser builtin tooltip that is being used. What browser are you using?
