### ISSUE TITLE
Query builder does not allow adding free text values in Where statement

### ISSUE THREAD

**Issue by Gabilehner** [grafana/azure-data-explorer-datasource#158]
When using the new query builder it is not possible to enter a value to the Where statement if it is not part of the auto-populated values.
I would like to be able to also add partial values.
It is the same case in the values and group by statement

**Comment by mckn** [comment]
hmm, you should be able to add an option by selecting this option:

<img width="925" alt="Skärmavbild 2020-09-28 kl  13 43 44" src="https://user-images.githubusercontent.com/172951/94428244-b182f480-0190-11eb-866a-7a3c515f1b95.png">
