### ISSUE TITLE
When the user just want to count, the query builder gives an error

### ISSUE THREAD

**Issue by avneraa** [grafana/azure-data-explorer-datasource#159]
When user wants to just show the count, they do not need to provide any specific column to count, this gives an error:
![image](https://user-images.githubusercontent.com/4261958/94425940-733c0400-0195-11eb-8799-09b122d9f0cb.png)

**Comment by mckn** [comment]
hmm, I see. You should not need to specify a column to count. I will add this as a valid option but I think in the long run we should probably improve the UI so this feels more natural in the UI.

**Comment by avneraa** [comment]
I would consider flipping the order, so the drop down shows all the relevant aggregation functions and the next blue label says "Column" and the dropdown shows the list of relevant columns. So if the user selects "count" then the column list is empty.  One huge benefit would be that it will be closer to how the user would write the query "summarize dcount(Col1)" so looking at the generated query is much more intuitive. 
As a side note, I suggested to rename "value columns" to "summarize" and remove the "summarize" from the "group by" label.
