### ISSUE TITLE
Support Azure National Clouds

### ISSUE THREAD

**Issue by djj0809** [grafana/azure-data-explorer-datasource#16]
I noticed that AAD endpoint currently is hard coded to Azure public cloud,
and according to https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud

National cloud | Azure AD authentication endpoint
-- | --
Azure AD for US Government | https://login.microsoftonline.us
Azure AD Germany | https://login.microsoftonline.de
Azure AD China operated by 21Vianet | https://login.chinacloudapi.cn
Azure AD (global service) | https://login.microsoftonline.com

I wish we can add an extra config for AAD endpoint (a dropdown or simple input) to support national clouds:)

Actually I made it locally, but I have no idea how to build the code (not familiar with js stuff), or I can try create a PR for you:)

**Comment by Gabilehner** [comment]
We do not plan to support Azure AD Germany as it is in deprecation process.
