### ISSUE TITLE
Value column is included in the "by" clause

### ISSUE THREAD

**Issue by avneraa** [grafana/azure-data-explorer-datasource#160]
When using the "count()" aggregation the column appears in the "by" clause, this is wrong:

![image](https://user-images.githubusercontent.com/4261958/94426112-bf874400-0195-11eb-9a08-60ddac08603f.png)

**Comment by mckn** [comment]
@avneraa great feedback, how should the query be formatted in this scenario?

**Comment by avneraa** [comment]
The value columns should not be included in the "by" clause, you need to simply remove the code that adds it to it. As a side not, I find the name "value columns" really misleading, I think that calling this "summarize" would be much clearer and look much more natural, especially if you remove the "(summarize)" from the "group by" area, so it reads like the query: |summarize ... by ...

**Comment by avneraa** [comment]
Hi Marcus, I updated the two issues with the answers.
