### ISSUE TITLE
Kusto: dashboard panel affected by local/UTC time differences.

### ISSUE THREAD

**Issue by sloutsky** [grafana/azure-data-explorer-datasource#161]
When building a dashboard - it seems that local times/UTC times are not translated right:

My local machine is configured for UTC+3 - but the the dashboard is showing times from Kusto (UTC times) as local times without UTC shift.

![image](https://user-images.githubusercontent.com/17802887/94515284-e2643780-022b-11eb-9600-95db0dbfbf2e.png)

**Comment by mckn** [comment]
> When building a dashboard - it seems that local times/UTC times are not translated right:
> 
> My local machine is configured for UTC+3 - but the the dashboard is showing times from Kusto (UTC times) as local times without UTC shift.
> 
> ![image](https://user-images.githubusercontent.com/17802887/94515284-e2643780-022b-11eb-9600-95db0dbfbf2e.png)

Have you checked the underlying data? Because when I am testing this it looks correct. The reason why the graph is cut down is that there are latency in the incoming data (I guess).

**Comment by sloutsky** [comment]
This still happens. Data latency is 5min - this can't explain 3h difference.
https://azuredataexplorer.grafana.net/dashboard/new?editPanel=2&orgId=1

![image](https://user-images.githubusercontent.com/17802887/95442274-d717b700-0963-11eb-8e3d-f5ed4c497dfa.png)

**Comment by mckn** [comment]
@sloutsky did you have time to look into this? Could you send me an example that I can reproduce this with?

**Comment by sloutsky** [comment]
The issue appears to be with the "limit 10000" appearing in the query, and it brings partial results
