### ISSUE TITLE
Explore: not displaying graph when results have multiple series

### ISSUE THREAD

**Issue by ms-anand** [grafana/azure-data-explorer-datasource#163]
When running query in Explore, if the results have only one series, then both graph & table options are displayed:
![image](https://user-images.githubusercontent.com/49461181/94520434-dd6cab80-025e-11eb-9a39-7f7fb59ded93.png)
However, when the results have multiple series, explore displays only table option:
![image](https://user-images.githubusercontent.com/49461181/94520580-186edf00-025f-11eb-9b4d-886660b993dc.png)
This happens only in Explore - dashboard panel seems to work fine:
![image](https://user-images.githubusercontent.com/49461181/94520717-55d36c80-025f-11eb-8f3e-6d4d5f3b0886.png)

**Comment by mckn** [comment]
This seems to have been an issue in Grafana core and should be resolved in 7.2 >
