### ISSUE TITLE
Data Source Configuration: Missing Required Fields

### ISSUE THREAD

**Issue by cjgibson** [grafana/azure-data-explorer-datasource#171]
I'm attempting to expose ADX to Grafana through this plugin, but when I go to actually create the data source within Grafana, a number of configuration fields appear to be missing or malformed:

![image](https://user-images.githubusercontent.com/4191354/95905859-34d64580-0d4e-11eb-809d-a42832e16885.png)

(In particular, I'm missing the option to provide a `Client Secret`, and am not sure what `{{ctrl.label}}` beneath `Query Optimizations` is supposed to be.)

I'm running the following versions, going to try using newer versions of Grafana / older versions of this plugin, but would appreciate any guidance if someone has seen this previously:
* Grafana: v6.7.2 (423a25fc32)
* azure-data-explorer-datasource: 3.1.0

Search phrases: `TypeError: Object(y.getTemplateSrv) is not a function. (In 'Object(y.getTemplateSrv)()', 'Object(y.getTemplateSrv)' is an instance of Object)`, client secret missing, cannot configure data source

**Comment by cjgibson** [comment]
For those that stumble upon this issue - upgrading Grafana to v7.1.5 (9893b8c53d) and leaving the plugin version unmodified at 3.1.0 fixes the above, and afterwards appears to work as expected.

**Comment by secustor** [comment]
With Grafana v7.0.0 the plugin system has been revamped and it seems this is the reason that this plugin has minimal version of v7.1.0  for plugin releases >3.0.0. 

If you want to use Grafana 6.x you have to downgrade to a plugin version 2.x.x   
https://grafana.com/grafana/plugins/grafana-azure-data-explorer-datasource

**Comment by cjgibson** [comment]
Thanks for that information @secustor! I made a quick change to this repo's README in order to include that detail - I'm not a huge fan of how I've phrased the dependency, but it'd be great if this kind of thing was publicized 😄
