### ISSUE TITLE
$__timeInterval in variables/annotations is always 00:00:01

### ISSUE THREAD

**Issue by Dammi87** [grafana/azure-data-explorer-datasource#177]
Using the $__timeInterval in a variable query can be quite handy, however it seems it doesn't update at all when time-range is changed. In an effort to capture this behaviour I created this variable.

![image](https://user-images.githubusercontent.com/23643258/96727918-1f42ca80-13a3-11eb-879b-9acf1bde3fbd.png)

Then, if look at what happens when we make a table with this query

```
datatable(timeInterval: timespan, variableInterval:string)[
    $__timeInterval, '$_grafanaInterval'
]
| project timeInterval, totimespan(variableInterval)
```

Notice that there is no change to the variable when changing the time-range, even after a refresh.

**1hr**
![image](https://user-images.githubusercontent.com/23643258/96729130-58c80580-13a4-11eb-988a-570f3ab87e99.png)

**24hr**
![image](https://user-images.githubusercontent.com/23643258/96729185-69787b80-13a4-11eb-8226-6b96e86a39a4.png)

I noticed this when working with the annotations and saw that they weren't being grouped according to the current binSize in use.

Tested on 
* Grafana version 7.2.0
* ADX plug-in version 3.1.0.

**Comment by joshhunt** [comment]
These ADX macros are only evaluated in the backend, but template variables are evaluated, so the $__timeInterval macro cannot be used in template variables.

**Comment by joshhunt** [comment]
We'll tag this as a feature request and look at how we can support this in the future

**Comment by Dammi87** [comment]
@joshhunt Is this feature request archived or is it only the project board? :)

**Comment by joshhunt** [comment]
Just the old project board. The team will still assess this feature request.
