### ISSUE TITLE
Grafana global variables not interpolated in alerts

### ISSUE THREAD

**Issue by brycefisher** [grafana/azure-data-explorer-datasource#182]
Queries used in alerts don't have any macros or variables expanded. This makes it very challenging to reuse panels for alerts.

Here's an example error (whitespace added) from a query that has a dashboard variable called `$BusinessUnit`:

```
Semantic error:
'MyTable
| where timestamp >= datetime(2020-10-22T18:23:46.551Z) and timestamp <= datetime(2020-10-22T18:28:46.551Z) 
    and business_unit == \"$BusinessUnit\"
| summarize count() by bin(timestamp, $__interval)
| order by timestamp asc'
has the following semantic error: 
  SEM0100: 'summarize' operator: 
    Failed to resolve scalar expression named '$__interval'.
```

Notice that neither `$__interval` nor `$BusinessUnit` was expanded in the query the alert generated.

Here's the same panel rendered as a line chart:
![Screen Shot 2020-10-22 at 11 35 17 AM](https://user-images.githubusercontent.com/220106/96915088-b28b0700-145a-11eb-9bc6-2f7cd9a52374.png)

**Comment by marefr** [comment]
Template variables support, like business unit example, are limited by https://github.com/grafana/grafana/issues/6557. 

The `$__interval` one though can be supported if  implemented in this data source.

**Comment by brycefisher** [comment]
@marefr thanks for the info! It would be great to support the `$__interval` and other time macros given the blocker from https://github.com/grafana/grafana/issues/6557

**Comment by sunker** [comment]
Seems like $__interval support is already [implemented](https://github.com/grafana/azure-data-explorer-datasource/blob/master/src/query_builder.ts#L17).
