### ISSUE TITLE
HTTP client should enforce a timeout

### ISSUE THREAD

**Issue by marefr** [grafana/azure-data-explorer-datasource#183]
The HTTP client in use seems to use the default of what Go provides. This is not optimal for production usage, see for example https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779, "Go’s http package doesn’t specify request timeouts by default, allowing services to hijack your goroutines.". 

Here's the code in question that gets a HTTP client. Not sure yet if it's uses Go's default HTTP client since it gets it from the oauth2 library:
https://github.com/grafana/azure-data-explorer-datasource/blob/015898bee2f69b557ec7dd85c648888c47104504/pkg/azuredx/azuredx.go#L119

One outstanding question is if this should be configured per plugin or per plugin data source instance on the data source configuration page. Maybe both, default timeout on global level with possibility to override on a data source instance by data source instance basis. This is maybe related to #165 that suggests adding a timeout to the data source configuration page and also discusses how to let service know how long to execute a request before it timeout.

**Comment by kylebrandt** [comment]
Would probably be good to set server side timeout to be a little less than our timeout as well, so get clean error messages and don't leave queries running server side.

Abandoned Draft PR of this before connection properties was added, should be able to add it to current properties I think:
 - https://github.com/grafana/azure-data-explorer-datasource/pull/109/files

Draft PR for similar issue for server side timeout in https://github.com/grafana/grafana/pull/28211
