### ISSUE TITLE
Issue with $__contains()

### ISSUE THREAD

**Issue by BernhardRode** [grafana/azure-data-explorer-datasource#188]
Hey, we want to build a chart and have the a counter shown in grafana:

We use the follwing query:

```
orders
| where $__contains(customerId, $customerId)
| project customerId, cartId, timeRecorded
| summarize count() by cartId
| count 
```

it throws an error:

```
Failed to execute query: Syntax error: Query could not be parsed: SYN0002: A recognition error occurred. ```
```
and shows the follwing expanded query:
```
orders
| where customerId in (''customer1'')
| project fleetId, tripId, timeRecorded
| summarize count() by cartId
| count
```

As far as i can see, there is a '' around the selected customer1, we also have set the variables $customerId all value to all, like described in the documentation. Then the query looks like this:

```
orders
| where customerId in (''all'')
| project fleetId, tripId, timeRecorded
| summarize count() by cartId
| count
```

But imho it should be something like:

```
orders
| where 1 == 1
| project fleetId, tripId, timeRecorded
| summarize count() by cartId
| count
```

We are using Grafana (v7.3.1 (6668161a88)) and azure-data-explorer-datasource (v3.2.1).

**Comment by konradsitarz** [comment]
I have the same issue and the same versions of Grafana and azure-data-explorer-datasource.

**Comment by konradsitarz** [comment]
It can be done without $__contains function.
you can use 
**where ColumnData in ($grafana_variable)**

I hope it helps.
