### ISSUE TITLE
Add autocompletion for materialized views in raw editor and visual editor

### ISSUE THREAD

**Issue by Bogdan-Catalin** [grafana/azure-data-explorer-datasource#191]
As it stands the only way to get autocompletion for materialized views is if we use managed schema and add mappings for them but it works only in the visual editor.

They can still be queried with the raw editor, but it would be nice to also have autocomplete.

**Comment by sunker** [comment]
Currently, we use [monaco kusto](https://github.com/Azure/monaco-kusto) code editor. The autocompletion is handled by this lib, so it's out of our control I'm afraid. 

The schema is loaded using the following query `.show schema as json`, and we're using the [setSchemaFromShowSchema](https://github.com/Azure/monaco-kusto#setting-a-schema) to register the schema. While debugging this, I noticed that the schema does indeed include definitions for materialized view. I wonder why monaco-kusto ignores them. @Gabilehner do you know?
