### ISSUE TITLE
When changing the view to Table view I still get the proposal to change to table view

### ISSUE THREAD

**Issue by Gabilehner** [grafana/azure-data-explorer-datasource#193]
When using the ADX query builder and constructing a query that does not return time series I get the proposal to change from Format of "Time Series" to "Table".
When I go and change it the error message does not go away.
![image](https://user-images.githubusercontent.com/37870771/103878726-7e30f980-50df-11eb-91ad-5f4d503eec7c.png)

**Comment by sunker** [comment]
For this to work you need to switch visualization in Grafana from Graph to Table. The `Format as` field in the query editor won't affect visualization, just the format of the data points being returned to Grafana. 

@kylebrandt, do we even need the Format as field? Backend returns data frames right, so we should be able to plot them in both tables and graphs?

**Comment by kylebrandt** [comment]
> @kylebrandt, do we even need the Format as field? Backend returns data frames right, so we should be able to plot them in both tables and graphs?

Yes. The frontend doesn't graphing the "long" format (Repeated timestamps, string columns as labels https://github.com/grafana/grafana/issues/22219) . So "Format as" set to "Time series" restructures the data to be in [dimensions](https://grafana.com/docs/grafana/latest/getting-started/timeseries-dimensions/). It is still a data frame, but a restructured data frame. This is also what we are expecting for time series input with alerting - so even if the frontend did support graphing without any Transforms, I'm not sure we would to change this.

**Comment by sunker** [comment]
I see, thanks for clearing that out @kylebrandt
