### ISSUE TITLE
Pie visual is not showing any data

### ISSUE THREAD

**Issue by Gabilehner** [grafana/azure-data-explorer-datasource#194]
I've created a KQL query that returns a simple result set of 15 records that looks like this (when shown as table visualization).
![image](https://user-images.githubusercontent.com/37870771/103878899-c3552b80-50df-11eb-821d-1b7c16ea6e11.png)
When I try to change it to Pie chart visualization it shows nothing.
I'm using the Pie Chart plugin.

**Comment by sunker** [comment]
The pie chart panels expects a time column to be present in the result. Add that and it should work.
