### ISSUE TITLE
When using the query builder each wrong key stroke or wait results in a big flashy error message

### ISSUE THREAD

**Issue by Gabilehner** [grafana/azure-data-explorer-datasource#195]
When I use the query builder, in case I type too slowly or do a mistake with a wrong key stroke I immediately get a big red error message which is not needed before I hit the run query.
For example below I got an error message since I'm still building my query.
![image](https://user-images.githubusercontent.com/37870771/103879754-f0eea480-50e0-11eb-8e9a-e962eeca3bbe.png)

**Comment by sunker** [comment]
The problem seems to arise when adding an aggregate without having a group by selected

**Comment by joshhunt** [comment]
![image](https://user-images.githubusercontent.com/46142/104195122-1ef22280-541a-11eb-9029-c0beb7e8f04e.png)

**Comment by joshhunt** [comment]
@Gabilehner Despite watching you trigger this bug yesterday, I haven't been able to reproduce this myself, and looking over the code nothing stands out as being the cause for this.

Are you able to reproduce this on the grafanastaging environment? Also are you able to provide detail reproduction steps? I'm wondering if this is database/table dependent, though that seems unlikely.

**Comment by Gabilehner** [comment]
Can you send me link to staging to try it out.
This reproduces very easily on my environment - if you'd like we can schedule a quick call to go over it.

Thanks,
Gabi

**Comment by joshhunt** [comment]
@Gabilehner Discussed this with @mckn and there are some parts where we can prevent incomplete queries from being formed, but that still doesn't resolve the issue where the query is submitted before you hit Run Query.

I'm happy for you to send through an invite so we can nail down a reproduction for this on my end

**Comment by joshhunt** [comment]
This is due to there being an auto-refresh interval defined for the dashboard. When the query is in an incomplete state and the auto-refresh kicks in, you may get an error like this.
