### ISSUE TITLE
Reduce in memory cache time

### ISSUE THREAD

**Issue by Ilanak** [grafana/azure-data-explorer-datasource#2]
Hi, 

I see that the in memory cache is c[onfigured to 30 seconds](https://github.com/grafana/azure-data-explorer-datasource/pull/1).

I'm trying to get my dashboard to refresh every 1s/5s, but due to the cache it gets updated only every 30s.

Is there a way I can change/disable the in memory cache?

**Comment by daniellee** [comment]
Closed by #3
