### ISSUE TITLE
Feature: add dashboard name as part of request id when sending query to ADX

### ISSUE THREAD

**Issue by erikbos** [grafana/azure-data-explorer-datasource#20]
Our Grafana deployment with ADX as backend is getting more and more popular.

Sometimes a dashboard get added that includes inefficient KQL queries. I'd like to hunt those down, or create a Grafana dashboard that shows the offenders ;-)

Would it be possible to add the name of dashboard to the HTTP header x-ms-client-request-id when sending a query to ADX?

Most clients appear to use the x-ms-client-request-id header, and its value appears to end up in the column ClientActivityId of .show queries's output.

**Comment by srclosson** [comment]
Moving to "needs investigation". 
Some questions:
Can we approach this more generically? For example, allow setting custom headers in the datasource configuration?

**Comment by erikbos** [comment]
https://github.com/grafana/azure-data-explorer-datasource/issues/166 is similar/related

**Comment by joshhunt** [comment]
Support for this was added in v3.3 https://github.com/grafana/azure-data-explorer-datasource/issues/166#issuecomment-761162598
