### ISSUE TITLE
Frequent Metric Request Errors with v3.3.0

### ISSUE THREAD

**Issue by brycefisher** [grafana/azure-data-explorer-datasource#201]
We just upgraded to v3.3.0 and are loving the ability to track users from Grafana to load in the system. Super helpful!

Sadly, we're seeing a lot of intermittent 500s like this:
![Screen Shot 2021-01-15 at 11 52 49 AM](https://user-images.githubusercontent.com/220106/104772455-50276700-5728-11eb-82be-26c7762bec3f.png)

We also see occasional 400 errors popping up that we didn't encount on the previous version.

This seems to affect all panels intermittently. Restarting Grafana hasn't helped. I'll try to provide more information, but I'm on Grafana Cloud so I'm opening a ticket there as well.

**Comment by sunker** [comment]
fixed in [this](https://github.com/grafana/azure-data-explorer-datasource/commit/7b108ee7548f25f6a7ea13c796803e42eb684835) commit
