### ISSUE TITLE
KQL editor issue : monaco.min.js failed to load from subpath

### ISSUE THREAD

**Issue by zameeransari** [grafana/azure-data-explorer-datasource#203]
What happened:
Kusto query inside KQL editor is not working as monaco.min.js failed to load from subpath. Grafana Helm chart YAML is given below for Nginx reverse proxy Grafana server setting:
==================================================

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"    
  enabled: true
  path: /monitoring/?(.*)  
  hosts:
    - subdomain.mydoamin.com

grafana.ini:
######################################
  server:
    domain: subdomain.mydoamin.com
    root_url: https://subdomain.mydoamin.com/monitoring
    serve_from_sub_path: false
######################################

**Environment details:**
- Grafana version: 7.3.6
- grafana-azure-data-explorer-datasource plugin version 3.3.1
- Backend: MySQL
- Data source type & version: MySQL 5.7
- OS Grafana is installed on: Azure Kubernetes Service version 1.15 with alpine base image
- Helm chart used: grafana/grafana:7.3.6
- Additional service integration : Grafana remote image rendering
- SSL enables: Yes
- Load Balancer: Azure private Load Balancer
- Reverse proxy: Nginx
- Image renderer version: grafana/grafana-image-renderer:2.0.0

![image](https://user-images.githubusercontent.com/5148363/106029281-eed1a180-60f2-11eb-990b-db257e6f0116.png)

monaco.min.js is not recognizing sub folder(/monitoring) and trying to load resource from the root ("/public"). However this bug seems fixed last year stated [here](https://github.com/grafana/azure-data-explorer-datasource/issues/8): https://github.com/grafana/azure-data-explorer-datasource/issues/8

Please help if you have came across such bug.

**Comment by joshhunt** [comment]
Hey @zameeransari just released a fix for this in v3.3.2. Please give it a try and let us know if you have any issues.
