### ISSUE TITLE
Issue with $__contains() in template variable queries

### ISSUE THREAD

**Issue by Grrrolf** [grafana/azure-data-explorer-datasource#214]
This seems to be related to #188.

I have various template variable queries which use the output from other template variables as input for where clauses. For these I use the $__contains() template macro for ease and efficiency.

For example, I have a query like this:

```
// template variable output_column
AggregationAll
| where $__contains(column_name1, $my_var1) 
| where $__contains(column_name2, $my_var2) 
| where $__contains(column_name3, $my_var3)
| where $__contains(column_name4, $my_var4) 
| distinct output_column
```

In ADX plugin 1.32 and 2.03 the following query is sent to ADX:

```
// template variable output_column
AggregationAll
| where 1 == 1 
| where 1 == 1 
| where 1 == 1
| where 1 == 1 
| distinct output_column
```
The above query is correct. 
However, when using ADX data source plugin 3.3.2 the following query is sent to ADX. 

```
// template variable output_column
AggregationAll
| where column_name1 in ('all') 
| where column_name2 in ('all') 
| where column_name3 in ('all')
| where column_name4 in ('all') 
| distinct output_column
```
As a result the query returns nothing.

We recently upgraded to from Grafana 6.7.4 to 7.4.3.

**Comment by joshhunt** [comment]
@Grrrolf I'm still looking into this, reproducing on my end, but have you seen this in the docs:

> If using the All option, then check the Include All Option checkbox and in the Custom all value field type in the following value: all. If $myVar has value all then the macro will instead expand to 1 == 1. For template variables with a lot of options, this will increase the query performance by not building a large where..in clause.

**Comment by Grrrolf** [comment]
Hello @joshhunt, 
Yes I have and just now I also double checked:
![image](https://user-images.githubusercontent.com/10052794/111189062-fde2b500-85b5-11eb-83f3-4cf65038e28a.png)
I have set this for all template variables.
