### ISSUE TITLE
Simplified query builder doesn't properly escape table names

### ISSUE THREAD

**Issue by mojanas** [grafana/azure-data-explorer-datasource#220]
Table names that have a . in them (ie `events.all`) need to be escaped when referenced in queries (`['events.all']`). The new simplified query builder doesn't do this, so the query fails with the error "Ensure that the expression is indeed a simple name."

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/53838891/113594554-7b21a880-95fd-11eb-8488-440aacc4e0a2.png)

**Comment by joshhunt** [comment]
Thanks for reporting!

**Comment by joshhunt** [comment]
I wonder if fields on tables also exhibit this issue. We'll look into it.
