### ISSUE TITLE
 Trying to use this with latest Grafana but it doesn't seem to be working.

### ISSUE THREAD

**Issue by viboga** [grafana/azure-data-explorer-datasource#23]
Error seen:
"Could not find executor for data source type: grafana-azure-data-explorer-datasource"

I see the Grafana documentation doesn't include support for azure data explorer yet. Looks like there is a change needed on the back-end as well. 

The changelog says "Time series queries now support alerting." -> What does this mean?

**Comment by nikoalch** [comment]
@viboga new release is out now. Please try again through grafana-cli or zip  https://grafana.com/grafana/plugins/grafana-azure-data-explorer-datasource
