### ISSUE TITLE
Annotations not showing up

### ISSUE THREAD

**Issue by MrFrankel** [grafana/azure-data-explorer-datasource#253]
Hey,

I'm trying to add query annotation as suggested in the Readme.
The query is working fine, but nothing is showing up on the charts.

Other data source annotation work.

Grafana v8.0.6 (68fe9e3431)

ClientEventLog
| project Timestamp=env_time, Text=version , Tags="tag1,tag2"

**Comment by vickyyyyyyy** [comment]
thanks for the report!

tried this with `8.0.6`, `8.1.1` and `7.3.7` and annotations don't seem to show up either - moved to the backlog
