### ISSUE TITLE
chore: migrate to Drone

### ISSUE THREAD

**Issue by vickyyyyyyy** [grafana/azure-data-explorer-datasource#257]
We are no longer using CircleCI for most of our builds, including `grafana`: https://drone.grafana.net/grafana/grafana

Migrate from CircleCi to Drone: https://drone.grafana.net/grafana/azure-data-explorer-datasource/settings

**Comment by sarahzinger** [comment]
I'm going to move this to Needs triage because our main branch is currently failing for reasons that I think are not code-related but are CI-related. Maybe we could try to prioritize picking this one up soon.
