### ISSUE TITLE
Grafana pie chart not working as expected for ADX

### ISSUE THREAD

**Issue by abhijit-tilak** [grafana/azure-data-explorer-datasource#260]
**What happened**:
We have a requirement to create Pie charts with ADX as the data source via Grafana. 
To make it happen, we have to write as many queries as the slices of the Pie to render it the way they want. This seems to be a bad solution to render a simple chart. 

**What you expected to happen**:

We expect to write one ADX query with either iff statements or case statements to create the Pie chart in Grafana.

**How to reproduce it (as minimally and precisely as possible)**:

1. Use a iff or case statement query from ADX
2. Go to Grafana and create a table visualization using that query
3. Try to convert the Table to a Pie chart and it will fail to render it the way you want
4. Eventually, each slice of the pie needs to be created as a separate query and then Grafana can render the pie chart

**Screenshots**
![image](https://user-images.githubusercontent.com/69059535/130256256-5d9b8b86-e349-4a6a-b611-21e18d0280e5.png)
![image](https://user-images.githubusercontent.com/69059535/130290980-4809d849-9b3f-44fb-a512-05659f8146cc.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.2.0
- Plugin version: "3.3.2",
- OS Grafana is installed on: Linux (redhat 7.6)
- User OS & Browser: Windows 10 64-bit & Chrome Version 86.0.4240.75 (Official Build) (64-bit)
- Others:

**Comment by sunker** [comment]
Thanks for reporting this @abhijit-tilak. 

In Grafana 7.5, we shipped a completely new implementation of the Pie Chart panel. This is from the new, Pie Chart panel docs. 
`The pie chart displays reduced series, or values in a series, from one or more queries, as they relate to each other, in the form of slices of a pie. ` So if possible, I suggest you upgrade to Grafana 7.5, or even 8.0 when the Pie Chart panel became stable, to solve this. 

If you're unable to upgrade and think this is a bug that needs to be fixed/investigated in the old Pie Chart panel plugin, please report an issue in the [Pie Chart panel repo](https://github.com/grafana/piechart-panel). For questions on how to write KQL queries, please refer to our [community site](https://community.grafana.com/). 

I'm gonna close this issue now, but feel free to re-open it if you feel the need to.
