### ISSUE TITLE
Expired credentials give ugly [object Object] error in query builder

### ISSUE THREAD

**Issue by joshhunt** [grafana/azure-data-explorer-datasource#269]
**What happened**:

When trying to make a new query using a data source that has expired credentials, the query editor errors out with `Could not load datasource schema: [object Object]`

**What you expected to happen**:

It displays an informative error message!

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure a data source using expired credentials. (Note for Grafanistas: currently our "Azure Data Explorer Github" credentials have expired
2. Create a new panel using that data source

**Screenshots**

![image](https://user-images.githubusercontent.com/46142/136937369-1e6e14f7-d7d9-4221-9496-c389f4f399c5.png)

The initial request from the data source appears to fail in the frontend with error 401:

```json
{
    "Message": "",
    "Error": "HTTP error: 401 Unauthorized - {\"Message\":\"Authorization has been denied for this request.\"}",
    "StatusCode": 401
}
```

**Comment by iwysiu** [comment]
I think this has gone away, since it currently returns `Could not load datasource schema due too: Azure query unsuccessful` which is a more helpful response.

**Comment by andresmgot** [comment]
well, that's still not that helpful since it doesn't show the reason of the error. The goal of this PR was to show the error message.  Is that something we can patch?
