### ISSUE TITLE
Plugin suddenly stopped working. Refuses to load with "Modified signature" error.

### ISSUE THREAD

**Issue by dg-eparizzi** [grafana/azure-data-explorer-datasource#271]
![image](https://user-images.githubusercontent.com/72451869/139860935-2f7a707b-3679-435f-b657-80484bf1a633.png)

**What happened**:

This grafana-azure-data-explorer-datasource plugin suddenly stopped working.

**What you expected to happen**:
Continue working as usual.

**Anything else we need to know?**:
We're running Grafana 7.5.11 via Docker (version is fixed) and using environment variables to install plugins.

`GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-azure-monitor-datasource,natel-discrete-panel,vonage-status-panel,flant-statusmap-panel,blackmirror1-statusbygroup-panel,grafana-piechart-panel,michaeldmoore-annunciator-panel`

For some reason the Azure Data Explorer plugin is broken. We've even added the following environment variable to tell Grafana to load that plugin anyway, but it still refuses to load.

`GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-azure-data-explorer-datasource`

Running a fresh `docker run...` seems to work, so the plugin is not broken. Somehow the instance has something related to this plugin broken and stored somewhere (I couldn't find anything related to this plugin in the database).

How can I force Grafana to re-download and re-install this plugin?

**Environment**:
- Grafana version: 7.5.11
- Data source type & version: Azure Data Explorer (latest)
- OS Grafana is installed on: Linux on Azure App Service for Linux (Docker)

**Comment by sarahzinger** [comment]
@dg-eparizzi thank you so much for reporting this issue! 

Unfortunately I haven't figured out how to recreate the issue myself just yet, but I'm curious when did this start happening for you? Was it after upgrading Azure Data Explorer to version 3.5.1? Do you see the same issues if you downgrade to 3.5.0 or 3.4.1 ? 

We did recently change our release process for this repo and ran into a few hiccups along the way, so I'm thinking it's plausible something about the most recently release caused the issues, although it's odd I don't see the same issue in our cloud environment. Are you able to look at the MANIFEST.txt file for the azure-data-explorer-datasource plugin that you're running and let me know the timestamp you see there?

**Comment by dg-eparizzi** [comment]
I could not reproduce it on a fresh instance so I simply ended deleting the plugin folder and re-installed it.


_______________________________

Emiliano Parizzi

Lead Software Development Engineer

Performance Analyzer Team

doosangridtech.com<http://www.doosangridtech.com/>

***@***.***>
[cid:67f3bfd6-b8f5-44d1-b8aa-74b1d04e63f1]
________________________________

**Comment by sarahzinger** [comment]
Ah ok. Sorry about that! Will close this then, but if this reappears we can reopen it again. Thanks anyway.
