### ISSUE TITLE
KQL Editor broken 

### ISSUE THREAD

**Issue by pahansen** [grafana/azure-data-explorer-datasource#284]
**What happened**:
Since today we are not able to use the KQL query editor anymore. It is only possible to query data when using the "Builder". Changes can not be saved in KQL editor, tables are not detected, "Run Query" button does not trigger searches and intellisense is not working anymore. 

Additionally, the "Builder" also breaks when going back and forth between Builder and KQL Editor.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Use raw Query in KQL editor and try to edit query.

**Screenshots**
![image](https://user-images.githubusercontent.com/39408669/143039751-6e93689a-c4d9-482b-8e7d-4b5a8b0bee33.png)
![image](https://user-images.githubusercontent.com/39408669/143039853-e1642e59-8996-4293-8017-2a937bca18e9.png)
![image](https://user-images.githubusercontent.com/39408669/143040172-3a7e6db7-1b0d-43a5-a31d-eabf33e162d9.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.6
- Plugin version: 3.6.0
- OS Grafana is installed on: Docker (locally)
- User OS & Browser: Chrome
- Others:

**Comment by FVE-DUCO** [comment]
I have the same!
Environment:

    Grafana version: 8.2.5 
    Plugin version: 3.6.0
    OS Grafana is installed on Linux
    User OS & Browser: Windows, Firefox
    Others:

**Comment by andresmgot** [comment]
Hi,

Thanks for reporting the issue. This is related to https://github.com/grafana/azure-data-explorer-datasource/pull/276 that was just released in 3.6.0. I am going to take a look to the issue but in the meantime, you can downgrade to the previous version (3.5.1). Sorrry for the inconveniences!

**Comment by andresmgot** [comment]
@FVE-DUCO @pahansen released 3.6.1 with the same editor than before. That should solve your issues.

**Comment by cdeil** [comment]
We also ran into this issue today. Not sure if it helps, but FWIW this is the query error we got:
```
Failed to execute query: Azure HTTP "520 InternalServiceError": "name\r\nParameter name: Argument 'name' is empty: at .ctor in C:\\source\\Src\\Engine\\DataNode\\Common\\Entities\\DatabaseIdentifier.cs: line 87
```

**Comment by shacharz** [comment]
I ran into the same problem, with plugin version 3.6.1.

```
Grafana version: 8.2.5
Plugin version: 3.6.1
OS Grafana is installed on: Docker (locally)
User OS & Browser: Edge (Chromium)
Others:
````

**Comment by andresmgot** [comment]
hi @shacharz, 3.6.1 does not contain the same editor than 3.6.0 so your issue should be different. Can you elaborate about the error you are getting?

**Comment by shacharz** [comment]
my bad, I didn't have the latest plugin version. (FWIW it's not really clear how to see plugins version number, and one can only see whether it's the latest or not)
