### ISSUE TITLE
Unable to render timeseries result from `make-series`

### ISSUE THREAD

**Issue by sanderaernouts** [grafana/azure-data-explorer-datasource#292]
**What happened**:
Using the ADX make-series queries from one of the documented example does not produce a graph

**What you expected to happen**:
The ADX make-series query should have shown a graph

**How to reproduce it (as minimally and precisely as possible)**:
Run this query (from the examples):
```
let T = range Timestamp from $__timeFrom to ($__timeTo + -30m) step 1m
  | extend   Person = dynamic(["Torkel", "Daniel", "Kyle", "Sofia"])
  | extend   Place  = dynamic(["EU",     "EU",     "US",   "EU"])
  | mvexpand Person, Place
  | extend   HatInventory = rand(5)
  | project  Timestamp, tostring(Person), tostring(Place), HatInventory;

T | make-series avg(HatInventory) default=double(null) on Timestamp from $__timeFrom to $__timeTo step 1m by Person, Place
  | extend series_decompose_forecast(avg_HatInventory, 1) | project-away *residual, *baseline, *seasonal

```

**Screenshots**
<img width="965" alt="image" src="https://user-images.githubusercontent.com/6184673/144595305-bf1ffa5f-a86d-4e85-a2cf-8b3dd9db1de4.png">

**Anything else we need to know?**:
In table format the data looks like this:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/6184673/144595675-dfb44a13-7478-4c32-b80d-edfa1d3d6f11.png">

From the screenshot it seems that all columns are detected as string and the timestamp column is not recognized as time in this `make-series` format.

**Environment**:
Grafana Cloud

**Comment by sanderaernouts** [comment]
I did some further digging through the source code and from the examples, test data and implementation I see that the ADX series `Timestamp` column is of type `dynamic` in the example responses however it is specified as a `datetime` column in the metadata which seems to be parsed by the datasource. 

However if I run the example queries from grafana cloud the `Timestamp` column is detected as a `string`. I can't see from the query results if that metadata is missing but is it possibly the response changed and the metadata which specifies `Timestamp` as a `datetime` is either in a different place or no longer there?

**Comment by sanderaernouts** [comment]
@vickyyyyyyy  any ideas on this? I wanted to try out Grafana Cloud but this is holding me back currently

**Comment by sunker** [comment]
Thanks for creating this issue @sanderaernouts. 

When testing this locally with the latest version of the plugin and the latest main of Grafana, it's actually working as expected. See screenshot below. In the _Format as_ picker below the code editor, did you choose "ADX time series"?

![Screenshot from 2021-12-15 14-07-03](https://user-images.githubusercontent.com/2388950/146192070-47457658-821c-4321-9c21-f1ef72a2f86b.png)

**Comment by sanderaernouts** [comment]
I see now that I'm using the `Azure Monitor` data source. Is that a different datasource implementation?
![image](https://user-images.githubusercontent.com/6184673/146199436-170b60f6-de45-45ac-9401-39d4f379a869.png)

**Comment by sunker** [comment]
Yes you'll need to install the [Azure Data Explorer data source](https://grafana.com/grafana/plugins/grafana-azure-data-explorer-datasource/). It's an external plugin. 

I'll close this issue.
