### ISSUE TITLE
$__timeFilter on a column that has dashes in its name does not work

### ISSUE THREAD

**Issue by astafan8** [grafana/azure-data-explorer-datasource#296]
**What happened**:

I get the following weird error when using query builder in grafana with azure data explorer data source:

```
Failed to execute query: Azure HTTP "400 BadRequest": 
"Request is invalid and cannot be processed: Syntax error: SYN0002: A recognition error occurred. [line:position=2:107]. 
Query: '['fridge-telemetry-from-hub']\n| where TimeGenerated >= datetime(2021-11-20T23:00:00Z) and TimeGenerated <= datetime(2021-11-22T22:59:59Z)(messageProperties_iothub-creation-time-utc)\n| summarize by '"
```

**What you expected to happen**:

The query builder would work and return results from the underlying adx resource.

**How to reproduce it (as minimally and precisely as possible)**:

See the screenshot below. Likely have an adx table with datetime column that has dashes in it's name.

**Screenshots**

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/15662810/146452531-99cdaab7-0712-4bdc-9716-f0e3a2b32210.png">

**Anything else we need to know?**:

I think the issue is in this regexp, the column names that have dashes do not work with the ``$__timeFilter(column-name)`` syntax:

https://github.com/grafana/azure-data-explorer-datasource/blob/919c9dbdeae97589ceb3ef2d70a1d07fd7174c9e/pkg/azuredx/models/macro.go#L36-L38

<img width="484" alt="image" src="https://user-images.githubusercontent.com/15662810/146453355-d1739dc2-7532-4058-8d90-c26375ca779e.png">

**Environment**:

- Grafana version: Grafana v8.3.3 (30bb7a93ca)
- Plugin version: 3.6.1
- OS Grafana is installed on: linux container
- User OS & Browser: Windows 10, Edge
- Others:

**Comment by fridgepoet** [comment]
Thank you @astafan8!

**Comment by fridgepoet** [comment]
Need to surround these column names with quotes: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/schema-entities/entity-names#identifier-quoting

**Comment by fridgepoet** [comment]
Thanks again @astafan8!
