### ISSUE TITLE
Pie Chart issues

### ISSUE THREAD

**Issue by NateZimmer** [grafana/azure-data-explorer-datasource#30]
Hey, great plugin though i'm struggling getting the data to work with the pie chart. 

I set `Format As`: Table
![image](https://user-images.githubusercontent.com/1478536/64932341-db76ac80-d803-11e9-8dcb-480f7f3267e3.png)
Then my query returns the following: 

| Key | Value |
| ---- | ----- | 
| Key1 | 40 | 
| Key2 | 50 | 

However, I get no pie chart. 
Panel error: 
```
TypeError: Cannot read property 'length' of undefined
```

**Comment by erikbos** [comment]
Are you share a Kusto query that produces this particular error? (It might help to find the issue.)

**Comment by NateZimmer** [comment]
Hmm, question right back at you. Can you produce a single table based query that actually generates a proper pie chart? 

Not sure this is of much help but this is in essence the query

```
MyTable
| summarize count() by Key
| extend Value = todouble(count_)
| project Value,Key
```

No matter how I format the data whether time-series or tabular, I can't seem to make the pie-chart plugin happy. Any ideas would be neat.

**Comment by erikbos** [comment]
I haven't used the piechart plugin (Tufte..) https://community.grafana.com/t/pie-chart-plugin-example/9068 gives a bunch of hints that help. (Also peculiar metric naming though)

<img width="529" alt="Screenshot 2019-09-26 at 07 34 39" src="https://user-images.githubusercontent.com/1421163/65660917-77888b00-e030-11e9-8010-3b5628ec3298.png">

**Comment by NateZimmer** [comment]
Thanks! That helps some. My take away from that is you can't use the Grafana "Table" option yet with kusto. To get it to accept my table, I had to append a column with an arbitrary date and config grafana to see the data as time-series 

```
MyTable
| summarize count() by Key
| extend Value = todouble(count_)
| project Value,Key
| extend timestamp = datetime(2019-09-12T15:46:17.954Z)
```
![image](https://user-images.githubusercontent.com/1478536/65775426-c7855180-e105-11e9-89bf-5d54af9e7aa0.png)

The legend naming is quirky though and not sure how to fix it: 
```
Value { Key = Key1 }: 40 (44.44%)
```
Hopefully there is some way to just make it: 
```
Key1
```

**Comment by erikbos** [comment]
I think it's unavoidable at the moment given that v2 label a metric based on "additional" columns and the requirement of the pie chart plugin to deliver three columns..

**Comment by PhineasJiang** [comment]
I'm using latest version of grafana & pie chart panel plugin, while I found it doesn't show anything even with the "timestamp" field defined.
I tried to use the following code you mentioned for drawing the pie chart:
`let Source = datatable(timestamp: datetime ,metric: string ,value: long )[
    datetime(2020-01-01), 'value1', 32,
    datetime(2020-01-01), 'value1', 44,
    datetime(2020-01-01), 'value1', 66,
    datetime(2020-01-01), 'value1', 32
];
Source`
But it doesn't show anything. In other places, they both suggest to have a "time" filed, while time filed is a keyword in ADX, which can't be used in "project" renaming.
Do you have some ideas ?

**Comment by Caryptis** [comment]
Same here as with @PhineasJiang. No chart, no errors.

**Comment by vprokopenko** [comment]
+1 No chart, no errors.

Kusto query is following:
datatable (Date:datetime, Name:string, Count:int)
    [datetime(2019-08-28T13:19:03.4712224Z), "Metric1", 233833499,
     datetime(2019-08-28T13:19:03.4712224Z), "Metric2", 36811,
     datetime(2019-08-28T13:19:03.4712224Z), "Metric3", 0]

Also it used to work before we updated the Grafana to the latest version.

**Comment by DannyArr** [comment]
This is still an issue, using Grafana 7.3.5 with the Pie Chart plugin 1.6.1. Example query:

`datatable(name:string, value:int)[
"thing1",100,
"thing2",50
]
| extend timestamp = datetime("01-01-2020")`

Getting the error: "Cannot read property 'length' of undefined"

Dashboard JSON:

`{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 10,
  "links": [],
  "panels": [
    {
      "datasource": "DIGITAL-UAT",
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": null,
            "filterable": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "showHeader": true
      },
      "pluginVersion": "7.3.5",
      "targets": [
        {
          "appInsights": {
            "dimension": [],
            "metricName": "select",
            "timeGrain": "auto"
          },
          "azureLogAnalytics": {
            "query": "datatable(name:string, value:int)[\n\"thing1\",100,\n\"thing2\",50\n]\n| extend timestamp = datetime(\"01-01-2020\")",
            "resultFormat": "time_series",
            "workspace": "ace3f7fe-ff58-40e0-a15e-cc51e5cd5abe"
          },
          "azureMonitor": {
            "aggOptions": [],
            "dimensionFilter": "*",
            "dimensionFilters": [],
            "metricDefinition": "select",
            "metricName": "select",
            "metricNamespace": "select",
            "resourceGroup": "select",
            "resourceName": "select",
            "timeGrain": "auto",
            "timeGrains": [],
            "top": "10"
          },
          "insightsAnalytics": {
            "query": "",
            "resultFormat": "time_series"
          },
          "queryType": "Azure Log Analytics",
          "refId": "A",
          "subscription": "8aae5d53-f263-479e-959c-0c67619ac334"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Panel Title",
      "type": "table"
    }
  ],
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Pie Chart",
  "uid": "xTROzP1Mk",
  "version": 2
}`

**Comment by joshhunt** [comment]
Ultimately this is due to an incompatibility between newer data formats the grafana SDK uses, and the older Pie chart panel which unfortunately has been that well supported (and [discourged from being used](https://blog.funnel.io/why-we-dont-use-pie-charts-and-some-tips-on-better-data-visualizations)).

**Comment by svkempf** [comment]
Is there any news about this?
I have the very same issue: Need to present Pie Chart but: No chart and no error message.

My Grafana Version is 7.4.3

**Comment by sunker** [comment]
Since version 7.5.0 of Grafana, it ships with a new, improved and officially supported version of a pie chart plugin. The problem described in this issue should not appear in the new pie chart plugin. So if possible, please upgrade to a Grafana version >  7.5.0. 

I'll close this issue now, but feel free to reopen it if you're still encountering problems after upgrading.
