### ISSUE TITLE
Query text is being populated with long delay

### ISSUE THREAD

**Issue by gilkgit** [grafana/azure-data-explorer-datasource#31]
Many times, the query text takes a lot of time to appear, ~10-20 sec and in times even more than 30 sec.
Maybe it's due to the syntax highlighting and auto complete feature (?)
I have a big cluster containing many databases with lots of tables and functions. possibly there's a sequential request and processing of that cluster and databases sachems before populating the query text(?)

**Comment by joshhunt** [comment]
@gilkgit I know it's been a while, but are you still seeing issues around this? I haven't been able to replicate this, but then I don't have access to clusters with many tables.

**Comment by sarahzinger** [comment]
Going to close this due to inactivity, but if it's still an issue we can open a new issue thanks!
