### ISSUE TITLE
Query builder: Unable to list filter values when the key include spaces

### ISSUE THREAD

**Issue by savastosic** [grafana/azure-data-explorer-datasource#318]
**What happened**:

Got a 400 error when trying to select information from a database table in ADX. My running theory based on the error, is that the ADX connector queries cant load data from an ADX table column with a "space" in the name. See the GIF below for details.
The connector properly loads all other columns.

**What you expected to happen**:

I expect to see the dropdown list of Truck IDs.

**How to reproduce it (as minimally and precisely as possible)**:

1. Using the ADX connector as a data source (Make sure to have a column with a space)
2. Open the dashboard builder
3. Select the ADX connection as a data source
4. Select the database
5. Select the table
6. Filter "where XXXXX ==" being the column of interest

**Screenshots**
GIF of Error:
![Animation](https://user-images.githubusercontent.com/90868835/152576405-2eb3ad96-a0d8-48d3-a14b-635e0b47dd41.gif)

Image of it working normally for a different tag:
![image](https://user-images.githubusercontent.com/90868835/152577179-6ff516d4-4ed6-4c5a-89b4-894e24770964.png)

**Anything else we need to know?**:

**Environment**:

- Grafana version: v8.3.5
- Plugin version: 3.6.1
- OS Grafana is installed on: Windows (but using a cloud instance)
- User OS & Browser: Chrome
- Others:

**Comment by andresmgot** [comment]
I am able to reproduce the issue running the same query that the plugin uses to obtain filter values:

```
DestinyActivities
| where $__timeFilter(TimeGenerated)
| where isnotempty(Truck ID)
| take 50000
| distinct Truck ID
| take 251
```

The correct syntax, when the field includes a space, is to wrap the string with quotes and brackets:

```
DestinyActivities
| where isnotempty(["Truck ID"])
| take 50000
| distinct ["Truck ID"]
| take 251
```

**Comment by taleena** [comment]
@savastosic is the answer above enough to get you what you need or are you running into anything else? Or did you find that this worked without the quotes and brackets in other spots?

**Comment by savastosic** [comment]
@taleena, this doesn't really resolve it. It is more of a temporary workaround for myself. The users on my client side will not be editing the ADX query to get their results. They rely on the query building and drop down filtering to select the appropriate tags.
