### ISSUE TITLE
New v2 plugin cannot decode all database responses anymore

### ISSUE THREAD

**Issue by erikbos** [grafana/azure-data-explorer-datasource#32]
I just deployed version 2 of the plugin on a testbox, and noticed that the data source has issues decoding the database response. (these queries run fine with the v1.3)

Error messages:

> failed to extract value '2803112.0' as a go of type string, column type is and a go type of json.Number

or

> failed to extract value 'false' as a go of type string, column type is  and a go type of bool

The queries below are not the ones I am using but work to reproduce the errors:

*Issue 1*

Query: ".show databases"
Visualisation: transform to Table
Columns: auto

![Screenshot 2019-09-25 at 13 14 35](https://user-images.githubusercontent.com/1421163/65596520-545dcd00-df97-11e9-8b2d-20b06691b9c7.png)

*Issue 2*

Query: ".show database ['ttapianalytics-westeu-db'] extents | | take 5 | project DatabaseName, ExtentId, OriginalSize, Blocks, ExtentContainerId, RowCount, MinCreatedOn"
Visualisation: transform to Table
Columns: auto

![Screenshot 2019-09-25 at 13 21 55](https://user-images.githubusercontent.com/1421163/65596885-22993600-df98-11e9-910a-3283965d77a1.png)

**Comment by srclosson** [comment]
The fixes for this were merged into master this morning as part of the work for #33. 

Please test, and let me know!

**Comment by erikbos** [comment]
I still get the same errors.. I deployed the plugin as suggested in https://github.com/grafana/azure-data-explorer-datasource/issues/33 (replace dist dir restart grafana/plugin backend) the "alias by" box confirms the new one is active I would say..

![Screenshot 2019-10-09 at 18 03 34](https://user-images.githubusercontent.com/1421163/66499672-8e16f380-eac0-11e9-80ca-d0e4498d7f3e.png)

**Comment by erikbos** [comment]
Also just print ("Hello World") does not appear to work for me with the test plugin you provided. Does that work for you? (Reinstalling 2.0.0 fixes it)

**Comment by srclosson** [comment]
Haha, nope. The fix for the aliasing broke the fix for this bug. I've already got a fix, but I'm going to test it a little more so as not to merge in anything that will impact you guys.

**Comment by srclosson** [comment]
The new 2.0 version should have fixed all of this. Please let me know if this does or does not work for you and re-open the issue if required.

https://grafana.com/grafana/plugins/grafana-azure-data-explorer-datasource
