### ISSUE TITLE
Increase unit-test coverage

### ISSUE THREAD

**Issue by andresmgot** [grafana/azure-data-explorer-datasource#327]
**What happened**:

We want at least a 50% coverage for all our plugins (both frontend and backend). At the moment, the coverage for ADX frontend code is 29.79%:

```
▶ yarn run jest --coverage
------------------------------------------|---------|----------|---------|---------|--------------------------------------------------------
File                                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                      
------------------------------------------|---------|----------|---------|---------|--------------------------------------------------------
All files                                 |   29.79 |    27.52 |   22.87 |   30.07 |                                                        
```

This can be highly affected by https://github.com/grafana/azure-data-explorer-datasource/issues/288

Note: the backend coverage is 57.1% so that is fine enough.

**Comment by vickyyyyyyy** [comment]
note: we should probably do this during/after our larger piece of work of refactoring ADX

**Comment by andresmgot** [comment]
After #369 the coverage is now ~60% so we can consider this task done.
