### ISSUE TITLE
Feature: Support all macros in Variable query editor

### ISSUE THREAD

**Issue by brycefisher** [grafana/azure-data-explorer-datasource#34]
## Context

 * Grafana v6.3.5 (67bad72)
 * Azure Data Explorer Datasource version 2.0.0

## What is Working

When creating a Variable for a dashboard, the `$__from` and `$__to` macros seem to expand into values from the timepicker as expected. Hooray! Example broken query showing expansion:

```
$__from .. $__to
```
![Screen Shot 2019-09-27 at 10 13 28 AM](https://user-images.githubusercontent.com/220106/65788599-48e1e180-e110-11e9-8a67-4aa7138f67f8.png)

## What's Not Working

When trying to use these macros, the expected expansion does not occur:

 * `$__timeFilter()` --> `timestamp between (datetime(<from>) .. datetime(<to>))`
 * `$__timeFrom` --> `datetime(<from>)`
 * `$__timeTo` --> `datetime(<to>)`

## Examples:

**$__timeFilter**
![Screen Shot 2019-09-27 at 10 11 25 AM](https://user-images.githubusercontent.com/220106/65788701-7d559d80-e110-11e9-83e9-4a5c6445e9b2.png)

---

**$__timeFrom and $__timeTo**

![Screen Shot 2019-09-27 at 10 11 52 AM](https://user-images.githubusercontent.com/220106/65788746-9b230280-e110-11e9-9426-89882d1f534f.png)

---

## Requested Change

I'd love to see the queries written inside Variable section expand as they do for queries written inside Panels (spelled out succintly here: https://github.com/grafana/azure-data-explorer-datasource/releases/tag/v2.0.0)

## Why this is a problem

 * "Bad" surprise -- users can't use the existing macro from Panels in template variables, but both feel like the same kind of thing
 * Hard to read -- because the query is only a single line and coercing a value from unix timestamp to Kusto datetime might take up a lot of that line, the query itself gets hard to read and easy to mess up

**Comment by srclosson** [comment]
Well defined, and a useful feature that other plugins support (ie: postgres).

Moving this into the backlog.
