### ISSUE TITLE
Generalize generation of scopes for all clouds

### ISSUE THREAD

**Issue by kostrse** [grafana/azure-data-explorer-datasource#356]
Currently, US Government cloud uses cluster URL as a scope and other clouds have predefined scope strings.

This can be generalized for all clouds:
1. All clouds may have the same logic based on the subdomain of cluster URL.
2. Proper top level domains for a given cloud (`*.windows.net`, `*.chinacloudapi.cn`) should be enforced. Requesting arbitrary scope based on free input of cluster URL should be discourage.

**Comment by fridgepoet** [comment]
> Requesting arbitrary scope based on free input of cluster URL should be discourage.

So were you envisioning some kind of verification on `clusterUrl`? Or something where we wanted to be sure that the `clusterUrl` passed in would never be a free input? Or did you have something else in mind?

**Comment by fridgepoet** [comment]
What would you envision for the errors returned by [normalizeAzureCloud](https://github.com/grafana/azure-data-explorer-datasource/pull/358/files#diff-4945be9fedff9efd9dc862ba5a30cfb155c5fc2b109030d838d05415c6c30c5fR16) and [resolveAuthorityForCloud](https://github.com/grafana/azure-data-explorer-datasource/pull/358/files#diff-27b85ab823a85d1aa0ba5d42b38e77909835a2e2f6e3ce9a6eaccc482abccc7fR60)?

**Comment by sunker** [comment]
Sounds good, but the tricky part here is testing. It took us months to get [this](https://github.com/grafana/azure-data-explorer-datasource/pull/258) tested in Mooncake cloud and in the USGov cloud.

**Comment by aangelisc** [comment]
@kostrse is this still an issue? Since we've added endpoint enforcement
