### ISSUE TITLE
DataSource not working with latest Grafana v6.3.5

### ISSUE THREAD

**Issue by atomaras** [grafana/azure-data-explorer-datasource#37]
Seems like v2 of the plugin is not working because the api/tsdb endpoint no longer exists?

![Grafana_ADX_Broken_Plugin](https://user-images.githubusercontent.com/3913941/66239667-5ae2f780-e6af-11e9-8773-b471757b28d3.png)

**Comment by briangann** [comment]
when you do a test datasource does it show green/connected?

**Comment by atomaras** [comment]
@briangann Yes

**Comment by srclosson** [comment]
@atomaras 
Would you try the latest version of the plugin, and let me know if this works for you? There have been a couple of fixes that I believe will be relevant here.

**Comment by srclosson** [comment]
@atomaras: I can probably create a build for you that you can install and try out, but better to just get the changes merged, and then just run `grafana-cli plugins update`. Do you know how to build the plugin?

**Comment by atomaras** [comment]
@srclosson Don't think so. I didn't see any build documentation in the README file. If I waited how long do you think it would take you to release a patch or make a custom build?

**Comment by srclosson** [comment]
There is a long series of fixes being merged now. We'll do a release and have you upgrade, then report back. I expect this won't happen today, but will be early next week for sure.

**Comment by srclosson** [comment]
@atomaras, you should be able to download 2.0.0 from https://grafana.com/grafana/plugins/grafana-azure-data-explorer-datasource. Let me know if this version works for you and if not, feel free to re-open this issue.

**Comment by atomaras** [comment]
@srclosson This is the version we had used. Has the data source code been updated without changing its version number?

**Comment by nshampur** [comment]
I just tried the latest docker image and it seems to work now. 
Any fixes gone in recently?

**Comment by nshampur** [comment]
I'm trying now to enable this via our CI/CD pipeline and can't seem to find the documentation 

Here is what I use for Azure Monitor DataSource

`- name: Azure
      type: grafana-azure-monitor-datasource
      orgId: 1
      typeLogoUrl: public/plugins/grafana-azure-monitor-datasource/img/logo.jpg
      access: proxy
      url: /api/datasources/proxy/5      
      jsonData:
        cloudName: azuremonitor
        subscriptionId: "{{AZURE_SUBSCRIPTION_ID}}"
        tenantId: "{{SERVICE_PRINCIPAL_TENANT_ID}}"
        clientId: "{{SERVICE_PRINCIPAL_CLIENT_ID}}"        
        azureLogAnalyticsSameAs: false      
      secureJsonData:
        clientSecret: "{{SERVICE_PRINCIPAL_SECRET}}"
      editable: false`
