### ISSUE TITLE
Template variable values with parenthesis result in 400 bad request

### ISSUE THREAD

**Issue by Grrrolf** [grafana/azure-data-explorer-datasource#370]
**What happened**:
When the template variable value has parenthesis included (e.g. "Product A (legacy), the value becomes malformed when inserted into the query. This results into a 400 bad request. 

**What you expected to happen**:
No malformed template variable values so that it does not result into a bad request, but a successful request.

**How to reproduce it (as minimally and precisely as possible)**:
1. I created a template variable and used the following query:
```
datatable(municipality:string)
["'s-Gravenhage", "Product l'ecole", "Product A", "Product A (legacy)", "Product B", "Product B (legacy)"];
```
2. I created a table panel and added this query:
```
datatable(field_1:string)
["'s-Gravenhage", "Product l'ecole", "Product A", "Product A (legacy)", "Product B", "Product B (legacy)"]
| where $__contains(field_1, $variables_all)
| project field_1
```
3. I then select a few values from the template variable/filter:
![image](https://user-images.githubusercontent.com/10052794/165638186-0cfbe09e-e73f-4d70-8e6c-a351573647b1.png)
4. I then run the query and the 400 bad request appears:
![image](https://user-images.githubusercontent.com/10052794/165638330-cb4d7ed6-8981-4527-a682-3507b95ffe0c.png)
When I click the raw query button, I see the following:
![image](https://user-images.githubusercontent.com/10052794/165638823-8e75aa0e-8057-44d3-850a-bd71fb2196d1.png)
![image](https://user-images.githubusercontent.com/10052794/165639262-88635825-a34c-47e2-ab84-18a0eb738292.png)

**Anything else we need to know?**:
No.

**Environment**:

- Grafana version: 8.5.0
- Plugin version: 3.7.1
- OS Grafana is installed on: Linux (ubuntu) and MacOS
- User OS & Browser: Brave / Google Chrome / Safari / Firefox
- Others:

**Comment by iwysiu** [comment]
Hi @Grrrolf ! Thanks for filing this issue.
After investigating, it seems that the [macroRegexp](https://github.com/grafana/azure-data-explorer-datasource/blob/bc992068b7761d92a01c99fd5a99524ce86e8655/src/query_builder.ts#L7) should be `/\$__([_a-zA-Z0-9]+)\((.*)\)/`

**Comment by Grrrolf** [comment]
Is there any ETA that you can or are allowed to give for a release which fixes this bug?

**Comment by aangelisc** [comment]
Hi @Grrrolf, I've got a PR open to fix this. Thanks!

**Comment by aangelisc** [comment]
Hi @Grrrolf, I can confirm the fix has been merged and will be released in the next version of the plugin 😊

**Comment by Grrrolf** [comment]
Hello @aangelisc, that's great news. Thank you so much! 😊 🙏

**Comment by aangelisc** [comment]
Hi @Grrrolf, version 4.1.7 is available now! If you have any further issues let us know 😊
