### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by yaelleC** [grafana/azure-data-explorer-datasource#375]
_Raised in : #371_ 

## Description
The error messaging for ADX can be quite confusing. In the example above the issue turned out to be with permissions but the error displayed was `Datasource i690Gzynk was not found`.

Having better error messaging would help users troubleshoot better and would avoid raising issues with us. Win-win!

### Screenshot
<img width=500 src="https://user-images.githubusercontent.com/42030685/167637016-8ae58154-a9ee-4046-bde6-ee6e1a644010.png" />

## Definition of done

- [ ] When a user does not have necessary permissions, the error message reflects that 
- [ ] Investigation into other error messages that could be improved (if any) and issues raised or fix implemented

**Comment by aangelisc** [comment]
Closing in favour of #578
