### ISSUE TITLE
Table is not able to load data after editing

### ISSUE THREAD

**Issue by FVE-DUCO** [grafana/azure-data-explorer-datasource#383]
**What happened**:
The table cannot load anymore

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
After updating to the 4.0.0, I edited a working table with Kusto query, saved the table and afterwards it does not load data anymore.  The table stays empty, but I know the data is available (also tested the query on the ADX database).   No error is shown.
Other tables which I haven't edited are not affected.  

**Anything else we need to know?**:
Reverting back to version 3.7.1 does not help for that edited table.  

**Environment**:

- Grafana version: 8.5.2
- Plugin version: 4.0.0
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Windows, Firefox
- Others:

**Comment by kevinwcyu** [comment]
Hi @FVE-DUCO,

I tried to repro by creating a query with v3.7.1 and then making minimal edits to my query in v4.0.0, but I was not able to reproduce it.

---

Have you tried reverting the dashboard version back to the state before you made the edits? You can do so by clicking the gear icon in the top right corner when you're in your dashboard, click "Versions" in the left hand side menu, and then restore the last working version.

You can also compare the changes between the 2 versions to see the diff between them. Could you provide that info please?

> No error is shown.
Have you checked the dev tools as well (console and network tab)? If you click on the Query inspector and click refresh, does the response show any error messages?

**Comment by FVE-DUCO** [comment]
Thank you  for the quick answer!
I tried reverting to the previous version and the table works again (thank you for the hint, i haven't thought about reverting the version but now the table at least works again :) ). 
If I try it again by changing a simple piece in the (rather complex) query (which is adding only 'and isnotempty(para)'), the refreshing works in the editor itself, then works when going back to the dashboard, but stops working when I change the value of a dashboard variable. This value changes the name of the DataSource, but I haven't changed anything there.  
![afbeelding](https://user-images.githubusercontent.com/26929912/169569603-08a92b6e-36a3-4040-9089-746175ca3f28.png)
When I compare the working with the non working dashboard version, I see something changed related to the datasource 
![afbeelding](https://user-images.githubusercontent.com/26929912/169566187-8ee351b0-8d7c-4beb-983f-8f25f46949cf.png)
I start to think that he doesn't correctly fills in the DataSource anymore:
![afbeelding](https://user-images.githubusercontent.com/26929912/169581588-40097d06-2c70-4a0b-9391-f7d5bdf3aa36.png)

`Have you checked the dev tools as well (console and network tab)? If you click on the Query inspector and click refresh, does the response show any error messages?`
I don't find these dev tools, but when I copy the raw query into the Query inspector, the query works again and gives results.

Very strangely, sometimes when I try everything to search for the root cause, it suddenly works.  But when I change the DataSource dasboard parameter, it stops working again...

**Comment by sarahzinger** [comment]
Hi @FVE-DUCO

I'm taking a look to see if I can recreate this error by setting of a datasource variable and using that and switching versions and I can't reproduce the error. :(

Would it be possible to share more about this query you're running and how you're using the variable? Also do you happen to remember any information on how you made this dashboard? For example was it imported or created manually?

I do notice in your screenshot of the data source it says `$Cloud` when I believe it should say `${Cloud}` which is interesting. I'm not sure how the curly braces would have been removed? Although when I try creating that by updating the dashboard's json directly and reloading in 4.0.0 it still seems to work so I don't know that that is the issue. 

It also seems like there might be other changes between the 2 dashboards, is there anything else you may be able to share with us? If you'd like you can send them to sarah.zinger@grafana.com and we can see if there's anything else that could indicate to us how to reproduce. 

It also sounded like you were unable to access dev tools, I think these 2 docs should be able to help you find them, and potentially see more error messages, which could help us try to debug:
- [How to look at dev tools console on firefox](https://firefox-source-docs.mozilla.org/devtools-user/web_console/)
- [How to look at network tab on firefox](https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/)

Thanks for your help in investigating!
