### ISSUE TITLE
Bug: Edit KQL

### ISSUE THREAD

**Issue by hfleitas** [grafana/azure-data-explorer-datasource#386]
**What happened**:

When you click Edit KQL, nothing happens.

**What you expected to happen**:

Query editor should appear

**How to reproduce it (as minimally and precisely as possible)**:

1. create Azure Managed Grafana resource
2. add ADX data source 
3. Explore data source, click Edit KQL.

**Anything else we need to know?**: imported [dashboard](https://github.com/anshulsharmas/F1_ADX/blob/master/grafana/F1%20ADX%20Statistics-grafana.json), then have to edit each panel to fix. 

**Environment**:

- Grafana version: Azure Managed Grafana
- Plugin version: panels 8.4.5, targets 3.7.1
- User OS & Browser: Win 11, Edge

**Comment by sarahzinger** [comment]
@hfleitas thanks for reporting your issue! Do you mind answering a few more questions to help us reproduce the issue:
- do you know what version of the azure-data-explorer plugin you're on (separate from your grafana version)? I'm able to see mine by navigating to `/admin/plugins/grafana-azure-data-explorer-datasource` I believe the latest is 4.0.0
- does this only happen after you import a dashboard or does it happen even when you create a new panel?
- do you see any errors in your browser's development console?

Thanks so much!

**Comment by sarahzinger** [comment]
ah sorry, I see you did list the version as 3.7.1, I must have missed that! I believe this issue was fixed in azure data explorer v4.0.0, is it possible to upgrade the datasource plugin within azure managed grafana? I see you've found the related [issue](https://github.com/grafana/azure-data-explorer-datasource/issues/325).

**Comment by hfleitas** [comment]
Hi @sarahzinger, in **Azure Managed Grafana** seems it doesn't allow updating plugins, I believe the service does it automatically on some cadence. I tested again the Edit KQL button today and it actually worked. It takes about **30 seconds** for the frame to load the first time, so I just had to wait longer. I think we can close the issue but will test again when 4.0.0 is published to the service.

**Comment by sarahzinger** [comment]
@hfleitas makes sense, thanks for letting us know, and definitely reach out if things don't seem fixed after 4.0.0
