### ISSUE TITLE
Feature: Plugin should support auth with MSI when running in Azure

### ISSUE THREAD

**Issue by cschertz** [grafana/azure-data-explorer-datasource#39]
Goal is to minimize cred management

**Comment by briangann** [comment]
Can you explain this with a little more detail?

**Comment by cschertz** [comment]
For context https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

Azure Managed Service Identity provides identities for VM and other resources types so they can be assigned roles in Azure and access to any resource that supports AAD Auth.     Basically it is a managed service principal.   When running on a VM in azure with MSI enabled instead of being passed a password to get an Auth Token a local endpoint on the VM is called to get the Auth token.  

It would be great if the plugin had an MSI mode for auth.   The overall goal being to get out of the business of credential management in code and config

**Comment by Gabilehner** [comment]
Can you elaborate more on how this scenario will work?
Which resource do you see using MSI? Azure Data Explorer cluster? or do you want to access Azure Data Explorer with MSI authentication?

**Comment by srclosson** [comment]
Well defined, and a useful feature. I agree, getting credential management, while maintaining security seems to be a reasonable request.

@cschertz : any information you can attach to this issue wrt MSI etc. will help expidite things.

Thank-you

**Comment by cschertz** [comment]
Sorry i missed the previous request for more info.    I

> Can you elaborate more on how this scenario will work?
I expect the config for the plugin we be like 3 values.  A flag indicating that MSI auth is being used.  A flag indicating if the MSI is a user or system msi and then if user msi it would pass the user MSI info.   If system MSI second value is not needed 

> Which resource do you see using MSI? Azure Data Explorer cluster? or do you want to access Azure Data Explorer with MSI authentication?
I want to access the ADX cluster with the MSI.     So that we dont have another SP to manage credentials for.
