### ISSUE TITLE
Materialized views are not displayed in the visual editor

### ISSUE THREAD

**Issue by andresmgot** [grafana/azure-data-explorer-datasource#399]
**What happened**:

It is possible to get suggestions in the raw editor for [materialized views](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/materialized-views/materialized-view-overview):

![Screenshot from 2022-06-07 12-06-55](https://user-images.githubusercontent.com/4025665/172354538-c7b50ca4-03a7-483b-ab8e-0ac2f5ad5fce.png)

But that table is not available in the visual editor:

![Screenshot from 2022-06-07 12-08-10](https://user-images.githubusercontent.com/4025665/172354728-75d2b56b-4469-49ce-8e9e-ead265cfec97.png)

**What you expected to happen**:

To be able to use a materialized view in the visual editor.

**Environment**:

- Grafana version: 9.0
- Plugin version: 4.0.2
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by andresmgot** [comment]
I noticed the same bug for [Functions](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/schema-entities/stored-functions).

Interestengly, if used a managed schema (Data source configuration  > Database schema settings > Use managed schema) and added entries for materialized views or functions, those will show up in the visual editor.

**Comment by shahdevangp** [comment]
I want to +1 this issue, I was going to report it but glad to see it registered here.

**Comment by andresmgot** [comment]
@shahdevangp we just released 4.1.1 fixing this and other bugs, let us know if you try it and have more feedback!
