### ISSUE TITLE
Using dashboard variable as the first filter in Query Builder leads to the query execution failure and scrolling issues

### ISSUE THREAD

**Issue by shahdevangp** [grafana/azure-data-explorer-datasource#402]
![variable query error and scrolling issue good size](https://user-images.githubusercontent.com/46785787/172814483-e523fa84-dd7b-424d-b91c-f39b7067aefe.gif)
**What happened**: Created a dashboard variable using column A from ADX table. In Query Builder, added the first filter as the same column and chose the dashboard variable as the value. When running the query using that variable, I get the error "_Failed to execute query: Azure HTTP "400 BadRequest": "Request is invalid and cannot be processed: Semantic error: SEM0100: 'where' operator: Failed to resolve table or column or scalar expression named 'WIF_FRPRR'"_". I have tried many different combinations for this variable but it doesn't seem to work. However, when I try to run the query with another variable, it works well. See the gif.

Also, when selecting "template variable", scrolling is very difficult. It doesnt allow to scroll smoothly to choose the template variable. Gif clearly shows the struggle.

**What you expected to happen**: Query should execute with the dashboard variable without any issues. This query works well natively in ADX. 

**How to reproduce it (as minimally and precisely as possible)**: See the gif. Create a dashboard variable and use it in the query builder or directly with KQL. To reproduce scrolling issue, see the gif. It's an easy one to reproduce.

**Screenshots**
see the attached GIF

**Environment**:

- Grafana version: 8.5.5
- Datasource Plugin version: dont know how to determine that
- User OS & Browser: Windows, Microsoft Edge

**Comment by shahdevangp** [comment]
I analyzed the query that Grafana is sending to ADX. Grafana is sending the variable value without the quotations "" and hence ADX is interpreting the variable value as a column and definitely cannot find it as a column in the table. I was able to reproduce this error with another dashboard as well.

**Comment by shahdevangp** [comment]
See the screenshot below 

![MicrosoftTeams-image (30)](https://user-images.githubusercontent.com/46785787/172850422-959231be-45f4-422f-943b-2d049ee106ae.png)

When I choose a variable value as Sensor_57, Grafana generates a KQL query and sends it to ADX. This is what ADX receives for this query:
windfarmtimeseries
| where timestamp >= datetime(2022-05-10T11:00:00Z) and timestamp <= datetime(2022-06-09T12:00:00Z)
| where Id_string in (Sensor_57)
| summarize avg(Value_double) by bin(timestamp, 30m), Id_string
| order by timestamp asc

And this query fails with "Request is invalid and cannot be processed: Semantic error: SEM0100: 'where' operator: Failed to resolve table or column or scalar expression named 'Sensor_57'" because Sensor_57 is not sent as String.

**Comment by shahdevangp** [comment]
To quote the template variable, the customer will need to Edit KQL. They want to use the query builder experience as that offers a low-code/no-code experience. So, the workaround is not an option for them. Also, the variable is an ADX query as well so we cannot put quotes manually for each value. We really need a fix.

**Comment by andresmgot** [comment]
Fixed in #413 and released in 4.1.1
