### ISSUE TITLE
Docs: Improve Configuration page

### ISSUE THREAD

**Issue by andresmgot** [grafana/azure-data-explorer-datasource#404]
**What happened**:

While going through ADX functionality, I found several things we can improve for the configuration page:

- [ ] Document settings
- [ ] Test uncovered settings
- [ ] Update tooltips. Some of them are not relevant or with wrong format.
- [ ] Remove toggle for default editor. It's not really useful and adds unnecessary clutter.

**Environment**:

- Grafana version:
- Plugin version: 4.1.0
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by andresmgot** [comment]
Hi @GrafanaWriter, it's the plugin README: 

https://github.com/grafana/azure-data-explorer-datasource#configuring-grafana

The only part documented are the "Connection Details" but it's also needed to document the rest of sections:

![image](https://user-images.githubusercontent.com/4025665/208860926-bf61b326-55cc-4ca6-ba45-b82af40be0b7.png)

**Comment by GrafanaWriter** [comment]
We are blocked on fixing this issue until we can free up resources.

**Comment by aangelisc** [comment]
Closing as OOD and the documentation has been updated since.

**Comment by bossinc** [comment]
Will be fully addressed with https://github.com/grafana/oss-plugin-partnerships/issues/757
