### ISSUE TITLE
Raw Query Editor not showing schema of dynamic fields

### ISSUE THREAD

**Issue by mrbar42** [grafana/azure-data-explorer-datasource#409]
**What happened**:
When writing a query using the raw KQL editor the auto-completion suggestions are not showing nested schema of dynamic fields.

**What you expected to happen**:
The visual query builder does show nested fields inside dynamic field so i expected that the raw editor will behave the same.

**How to reproduce it (as minimally and precisely as possible)**:
1. given an ADX datasource with a table that contains a dynamic field with nested fields
Example:

| Col1         | Col2     | Col3 |
|--------------|-----------|------------|
| value1 | value2      | {count: 1}        |

2. go to "Explore"
3. Make sure that the visual builder shows "Col3.count" in the fields list
4. switch to raw KQL editor
5. type "Col3."
6. The suggestions window doesn't show "count" as an option

**Anything else we need to know?**:
Visual Builder
<img width="370" alt="image" src="https://user-images.githubusercontent.com/12373774/173314858-da05a926-7226-43cd-9c5f-9a52486625b2.png">

Raw Editor
<img width="558" alt="image" src="https://user-images.githubusercontent.com/12373774/173314687-5d6ee331-3ceb-48e0-8def-dc42cafc362d.png">

**Environment**:

- Grafana version: v8.4.5 (4cafe613e)
- Plugin version: 3.7.1
- OS Grafana is installed on: Azure Managed Grafana
- User OS & Browser: macOS & Edge
- Others:

**Comment by kevinwcyu** [comment]
Thanks for raising this @mrbar42, I've added this to our team's backlog.

**Comment by andresmgot** [comment]
Hi, unfortunately there is actually not much that we can do here. We don't have control over the autocompletion features of the editor beacuse is something that https://github.com/Azure/monaco-kusto provides. This is something that should be requested in that repository.

Note that you find the same functionality limitation in the Azure portal query editor for Azure Data Explorer.

**Comment by aangelisc** [comment]
This issue still exists in the portal and I concur we cannot implement a fix on our side at the moment so I'm going to close this.
