### ISSUE TITLE
Query builder not working aftering updating the ADX plugin

### ISSUE THREAD

**Issue by shahdevangp** [grafana/azure-data-explorer-datasource#421]
**What happened**: I updated the ADX Grafana plugin to the latest version 4.1.1. After upgrading, I cannot choose any tables in the Query Builder. I get the error message as "Table schema loaded successfully but without any columns"

**What you expected to happen**: Query builder experience should work exactly the same way as it was working before.

**How to reproduce it (as minimally and precisely as possible)**: Update the plugin to the latest version and add a new panel or go to an existing panel.

![image](https://user-images.githubusercontent.com/46785787/177176092-7e6c1ec8-ef9f-46dc-b424-21332b72d0b3.png)

**Environment**:

- Grafana version: 9.0.3
- Plugin version: 4.1.1
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Windows 11, Microsoft Edge

**Comment by andresmgot** [comment]
Hi @shahdevangp,

I have run a quick test upgrading from 4.0.2 to 4.1.1 and I was not able to reproduce the issue. We would need more information to identify what's going on.

- From which version are you upgrading? Does works for you again if you downgrade to the previous version?
- Has there been any other change that may have caused this? (e.g. a change in the data source configuration)
- Are you able to see any error in the browser console or in the network tab? If you check the network tab, you should see a request for the `schema` of the database, this is the call used to retrieve the columns info:

![Screenshot from 2022-07-04 17-15-45](https://user-images.githubusercontent.com/4025665/177182538-749480e2-db22-40c5-ba19-a6aed37a876b.png)

**Comment by shahdevangp** [comment]
![image](https://user-images.githubusercontent.com/46785787/177311985-49ab8998-ffe4-481d-a1ba-54a73e8d8100.png)
[shahdevangp.grafana.net-1657018230661.log](https://github.com/grafana/azure-data-explorer-datasource/files/9045731/shahdevangp.grafana.net-1657018230661.log)

Please check the attached screen shot and the console log. Hope this helps.

**Comment by shahdevangp** [comment]
I don't remember my previous version. I am using Grafana Cloud. https://shahdevangp.grafana.net/
If you want to check from the backend, then feel free to do so.

**Comment by shahdevangp** [comment]
I had enabled Managed Schema setting in the data source plugin. I disabled it and it works.
