### ISSUE TITLE
Grafana table via Kusto not getting populated properly

### ISSUE THREAD

**Issue by shakerkms** [grafana/azure-data-explorer-datasource#437]
I’ve built a Grafana dashboard that is querying against 1ES kusto db & shows the results in a table format. I'm seeing that the table sometimes don't get populated properly (see screenshot below – OneSS Active PRs) . However, if I reload the page couple of times, it will populate properly. Unfortunately, the issue will pop up in another
table 🙁 I've ran the queries directly in kusto and it works fine (& fast).
![image003](https://user-images.githubusercontent.com/69259087/181073525-4c62a6aa-dbc2-4b25-8a4c-054cd5379c16.png)

**Comment by andresmgot** [comment]
Hi @shakerkms,

We will need more information to address what could be happening:

- Is it only a visualization issue? Meaning, if you click on the query editor and in the "Query Inspector", are you able to see the data there but not in the table.
- What query are you trying to execute? So we can try to reproduce it. Does the query return a large amount of data?
- Does it always behave the same? Is always the same information missing?

**Comment by shakerkms** [comment]
Hi @andresmgot - thanks for looking into it.
#1. It is not just a visualization issue. If I toggle "table view" in query inspector, I see the same issue
#2. Query doesn't return a large number of data and it runs fine in kusto directly
#3. It seems like it. All the panels are supposed to show the data in the same table format - PullRequestId, CreatedByDisplayName, CreationDate etc. and they only show CreationDate properly

**Comment by andresmgot** [comment]
This may be related to #436 and the plugin overloading the UI.

 - In the query editor, have you set the "Format as" field as "Table"? Also, does it help if you reduce the size of the query to, let's say 100 records?
 
![Screenshot from 2022-08-01 16-41-50](https://user-images.githubusercontent.com/4025665/182175796-27a9d33b-11fa-4041-b6f4-695d10afd44e.png)

- If the above does not help, can you let us know what query you are running to try to reproduce it?

**Comment by shakerkms** [comment]
Setting format as table seems to fixed the issue. Thanks for investigating.

**Comment by Grrrolf** [comment]
Hello @shakerkms ,

>  ![image](https://user-images.githubusercontent.com/10052794/183161740-1a19452d-5a56-4fc0-9316-d0aa3faf7d4c.png)


Whenever you see such an exclamation mark/triangle Grafana is trying to tell you something. Hover over the triangle with your mouse pointer to see what it is telling you. Usually it's about wrong formatting.

Based on @andresmgot you were already able to fix this issue 👍

**Comment by andresmgot** [comment]
Thanks for confirming! Let me close this issue then.
