### ISSUE TITLE
Port for pprof should only be started when environment variable is set

### ISSUE THREAD

**Issue by briangann** [grafana/azure-data-explorer-datasource#44]
Implement the following env variable so we can conditionally start the golang pprof port:

GRAFANA_PLUGINS_PPROF=pluginname

If that environment variable exists and matches the current plugin, enable the pprof port 6060

Currently the plugin always starts the port and can cause a conflict with other plugins. Only one plugin should be allowed to open this port.

**Comment by briangann** [comment]
fixed the variable name, should be `GRAFANA_PLUGINS_PPROF` and the parsing code needs to be fixed.

**Comment by sunker** [comment]
@briangann is this issue still relevant?

**Comment by vickyyyyyyy** [comment]
this has been integrated with sdk-go
