### ISSUE TITLE
Query Builder Fails on Aggregation in Alerts

### ISSUE THREAD

**Issue by greatvovan** [grafana/azure-data-explorer-datasource#469]
1. Go to Alerting.
2. On Alert Rules tab click New Alert Rules.
4. Select ADX data source for A query.
5. (If Query Builder is not enabled by default) switch to Builder.
6. Select database, table, and filter condition.
7. Click "+" next to Aggregate or Group by.

**Expected result:** query rebuild accordingly.

**Actual result:** error message

<img width="835" alt="image" src="https://user-images.githubusercontent.com/4903007/190460935-9a905b01-ea91-4f30-b5c8-8a4dc4453ee6.png">

If expanded, exception trace is printed as follows:

> An unexpected error happened
> Details
> Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
> 
>     at Fr (https://teckwat.grafana.net/public/plugins/grafana-azure-data-explorer-datasource/module.js:1:138127)
>     at div
>     at yn (https://teckwat.grafana.net/public/plugins/grafana-azure-data-explorer-datasource/module.js:1:111610)
>     at div
>     at div
>     at Ot (https://teckwat.grafana.net/public/plugins/grafana-azure-data-explorer-datasource/module.js:1:77290)
>     at eval (https://teckwat.grafana.net/public/plugins/grafana-azure-data-explorer-datasource/module.js:1:142530)
>     at ca (https://teckwat.grafana.net/public/plugins/grafana-azure-data-explorer-datasource/module.js:1:152821)
>     at Oa (https://teckwat.grafana.net/public/plugins/grafana-azure-data-explorer-datasource/module.js:1:160632)
>     at eu (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:3232:467)
>     at tu (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:3232:1023)
>     at div
>     at div
>     at div
>     at https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:639223
>     at g (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:1033209)
>     at So (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:640538)
>     at Oo (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:640656)
>     at h (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:5794:72)
>     at div
>     at D (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:8536:955)
>     at div
>     at Er (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/AlertingRuleForm.0b3a0d3ad412892726f6.js:134:177)
>     at div
>     at https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:642897
>     at g (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:1033209)
>     at l (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:1031254)
>     at zr (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:626246)
>     at t (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:559675)
>     at Hr (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:629786)
>     at Pr (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/AlertingRuleForm.0b3a0d3ad412892726f6.js:139:189)
>     at div
>     at Gr (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/AlertingRuleForm.0b3a0d3ad412892726f6.js:139:5445)
>     at B (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:928760)
>     at div
>     at div
>     at h (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:156:27)
>     at div
>     at Jr (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/AlertingRuleForm.0b3a0d3ad412892726f6.js:148:244)
>     at fieldset
>     at Uh (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:3351:366)
>     at div
>     at div
>     at _ (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/AlertingRuleForm.0b3a0d3ad412892726f6.js:13:30)
>     at ei (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/AlertingRuleForm.0b3a0d3ad412892726f6.js:148:1107)
>     at div
>     at div
>     at div
>     at t (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:710633)
>     at c (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:83:2765)
>     at div
>     at form
>     at R (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:926701)
>     at ii (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/AlertingRuleForm.0b3a0d3ad412892726f6.js:148:1395)
>     at yi.style (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/AlertingRuleForm.0b3a0d3ad412892726f6.js:171:49)
>     at eu (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:3232:467)
>     at tu (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:3232:1023)
>     at WithErrorBoundary
>     at n (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:979539)
>     at Dt (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:5466:10873)
>     at t (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:1048527)
>     at t (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:1050548)
>     at main
>     at Fe (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:5426:22350)
>     at t (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:1045145)
>     at div
>     at Ni (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:2479:1027)
>     at t.KBarProvider (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:290785)
>     at l (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:6109:28425)
>     at eu (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:3232:467)
>     at tu (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:3232:1023)
>     at y (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:2903758)
>     at u (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:6102:10956)
>     at l (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2449.def35241a3dcae812382.js:2:1031254)
>     at ln (https://grafana-assets.grafana.net/grafana-pro/9.1.3-e1f2f3c/public/build/2486.095bf9fec880b3ef01b4.js:5479:167)

**Anything else we need to know?**:

The same functionality works fine in Explore mode, the problem occurs in Alerting.

**Environment**:

- Grafana version: Cloud
- Plugin version: 4.1.5
- User OS & Browser: Chrome, latest

**Comment by yaelleC** [comment]
Hi @greatvovan , thanks for raising that issue and all these details.
I can indeed replicate the issue, however it seems to only be happening in alerting and not in the panel query builder 🤷‍♀️ 

I'll add @grafana/alerting-squad to this issue

**Comment by yuri-tceretian** [comment]
At first glance, this seems to be a front-end issue. Adding label

**Comment by yaelleC** [comment]
Agreed, I've got:

```
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

I'll take a look at it today
