### ISSUE TITLE
Allow setting default "Alias by" behavior in the datasource configuration page

### ISSUE THREAD

**Issue by gilkgit** [grafana/azure-data-explorer-datasource#47]
Allow setting default "Alias by" behavior in the azure-data-explorer-datasource general settings page.
This way, people who are opinionated about the chart presentation will not have to manually set "Alias by" field for each and every chart they own.

Also, people will be able to switch default presentation for all their charts in case they change their minds and assuming they didn't override the default behavior in the chart.

@srclosson 
@erikbos

**Comment by vickyyyyyyy** [comment]
This is a feature request that we can’t see prioritising any time in the near future. If this is a feature that the community still wants, please re-open this in discussions and we may consider it further if it gets more traction. Thanks!
