### ISSUE TITLE
ADX: Create dashboard for ADX adoption tracking

### ISSUE THREAD

**Issue by yaelleC** [grafana/azure-data-explorer-datasource#491]
Since https://github.com/grafana/azure-data-explorer-datasource/pull/488 and https://github.com/grafana/azure-data-explorer-datasource/pull/487 we have adoption tracking for ADX

We should create a new row for ADX in https://ops.grafana.net/d/Ad0pti0N 

Based on the dashboard for Azure: https://github.com/grafana/cloud-data-sources/issues/21

**Comment by andresmgot** [comment]
done!
