### ISSUE TITLE
Math expressions broken with OBO auth (no User and req.Headers)

### ISSUE THREAD

**Issue by kostrse** [grafana/azure-data-explorer-datasource#513]
**What happened**:

When using math expressions with OBO authentication, the `QueryData(ctx, req)` call doesn't receive `req.Headers`.

**What you expected to happen**:

OBO authentication should work and QueryData should receive user information and access token header regardless whether the call originated from a math expression or not.

**How to reproduce it (as minimally and precisely as possible)**:

1. Have #503 patched
2. Open a panel editor with ADX datasource
3. Add any two queries A and B which successfully return data
4. Add an expression, "Math", "$A + $B"
5. Set breakpoint [here](https://github.com/grafana/azure-data-explorer-datasource/blob/e25f75a831651e5825bef183496d778c87624f50/pkg/azuredx/datasource.go#L82)
6. Run math expression, see that value of `req.UserContext.User` is `nil` and `req.Headers` is `nil` too.

**Screenshots**

Error message of a panel containing a math expression:
![image](https://user-images.githubusercontent.com/1131253/202123363-adc5892d-59ed-400a-850e-37ecdd04ee83.png)

QueryData [here](https://github.com/grafana/azure-data-explorer-datasource/blob/e25f75a831651e5825bef183496d778c87624f50/pkg/azuredx/datasource.go#L82):
![image](https://user-images.githubusercontent.com/1131253/202124021-decb4135-93b8-4c81-8e28-5db9ddf046bc.png)

**Anything else we need to know?**:

This bug is hidden behind the #503 since any expressions are currently broken. But this is another issue which affects OBO authentication.

Related: https://github.com/grafana/grafana/issues/58793

**Environment**:

- Grafana version: main
- Plugin version: main
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by kylebrandt** [comment]
I am hoping this https://github.com/grafana/grafana/pull/58897 fixes this , @grafana/cloud-provider-plugins can perhaps test this week.

**Comment by kostrse** [comment]
@kylebrandt #58897  fixes` req.PluginContext.User` and `req.Headers` but `req.Headers` doesn't have `X-ID-Token` which is required for the OBO auth.
