### ISSUE TITLE
Fix typing of getCredentials/updateCredentials

### ISSUE THREAD

**Issue by kostrse** [grafana/azure-data-explorer-datasource#530]
Currently, `src/components/ConfigEditor/AzureCredentialsConfig.ts` uses type `DataSourceSettings<any, any>` for datasource options.

The typing needs to be reviewed, to avoid usage of `any`.

It's possible that typing of `DataSourceJsonData` and `S` type parameters of `DataSourceSettings` in `@grafana/data` is inaccurate.

`JsonData` and `SecureJsonData` are property bags and should allow random key/value access but they are not typed as such.

Original discussion here:
https://github.com/grafana/azure-data-explorer-datasource/pull/529#discussion_r1056159957

**Comment by aangelisc** [comment]
Closing this as this issue is more related to the underlying Grafana types than the data source specifically. We're also planning on rectifying this via the Azure React SDK.
