### ISSUE TITLE
Monaco bundle file is not cached

### ISSUE THREAD

**Issue by mrbar42** [grafana/azure-data-explorer-datasource#537]
### What happened:
Whenever a query is edited in raw mode (e.g. not with the visual builder) the Monaco editor is loaded.
The monaco.min.js file wights 6MB and for some reason caching is hard-disabled in the headers + the request url contains cache bust.

That means that every time the raw editor is presented the browser loads 6MB before the editor is shown.
example URL:
> https://*******.grafana.azure.com/public/plugins/grafana-azure-data-explorer-datasource/libs/monaco.min.js?_cache=1672575568412

Caching related response headers:
> Cache-Control: no-cache
Expires: -1

### What you expected to happen:
monaco.min.js maximizes caching capabilities of the server/CDN/browser.

### How to reproduce it:
1. edit a panel that uses an ADX data source
1. switch to raw mode

### Screenshots

<img width="879" alt="" src="https://user-images.githubusercontent.com/12373774/211776608-f7f1e0bc-5e96-4c59-ac52-984f2e84bccd.png">
I just so happened to work on a slow internet connection for a little while and this resource takes minutes to download, making the UI completely unusable for editing since it needs to load 6MB on every page load!

Obviously extremely slow connections should not be a strong reference point, but caching (large) resources feels elementary.

### Environment:
- Grafana version: v9.2.7.1 (0f96ed148c)
- Plugin version: 4.1.6
- OS Grafana is installed on: Azure Managed Grafana
- User OS & Browser: Any
- Others:

**Comment by andresmgot** [comment]
that editor is deprecated and should not be loaded with newer versions of Grafana and ADX. I believe you are hitting this issue: https://github.com/grafana/azure-data-explorer-datasource/issues/505 which prevent the plugin from loading the right version but that should be fixed in the latest version of the plugin (4.1.10). Can you check if upgrading solves your issue?

**Comment by bossinc** [comment]
@mrbar42 Have you managed to upgrade? Does this fix your issue?

**Comment by mrbar42** [comment]
Seem to be fixed, thank you very much!
