### ISSUE TITLE
Time filter within a variable query does't work

### ISSUE THREAD

**Issue by shaharmor** [grafana/azure-data-explorer-datasource#546]
**What happened**:

When trying to add a time filter to a query-based variable, the query fails.

Example query:

myTable
| where $__timeFilter(timestamp) // <-- This line makes the query fail
| take 10
| project columnName

**What you expected to happen**:

The query should use the timefilter when getting the data from ADX for the variable

**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**

**Anything else we need to know?**:

**Environment**:

- Grafana version: [v9.2.7.1 (0f96ed148c)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- Plugin version: 4.1.6
- OS Grafana is installed on: N/A
- User OS & Browser: Mac + Chrome
- Others:

**Comment by bossinc** [comment]
It doesn't look like we currently support time macros in template variable queries. @aangelisc please correct me if I'm wrong.

**Comment by shaharmor** [comment]
I also don’t think it is possible to reference other variables for even further filtering.

for example, if I have a “customer” filter and an “order” filter, I would want that when I filter for customer A, the orders variable will only show values for customer A.

should I open a different issue for this?

**Comment by andresmgot** [comment]
The `timeFilter` macro and other variables are supported. If you open the Query Inspector, you should be able to see how it's resolved, something like:

```
myTable
| where timestamp >= datetime(2023-01-26T08:23:09.677Z) and timestamp <= datetime(2023-01-26T08:38:09.677Z)
| take 10
| project columnName
```

The problem may be that the column `timestamp` may not exist. What is the error you are getting?

I also recommend upgrading to the latest version of the plugin to get rid of possible bugs.

**Comment by shaharmor** [comment]
@andresmgot it doesn't work.

I added this where clause to the query of the variable:
```
| where $__timeFilter(timestamp)
```

and the query is being sent with this line as is.

**Comment by shaharmor** [comment]
@andresmgot in a panel it works, but not in a variable query

**Comment by andresmgot** [comment]
ah, sorry, completely misread the description you are right @bossinc we don't support variables in variables queries. This would be a new feature.

We should refactor how template variables are written in the plugin. It's using the old `metricFindQuery` method, while it should use the same query editor as the panel.

**Comment by shaharmor** [comment]
I really think this would greatly improve the UX of using variables for filtering, as the values will only be the ones relevant and not all possible values

**Comment by taleena** [comment]
Overally, the fix alone for this was a small effort, but did additional work to improve the feature, which would count the overall time spent here closer to a medium.
