### ISSUE TITLE
metric request error

### ISSUE THREAD

**Issue by ManojRaheja** [grafana/azure-data-explorer-datasource#55]
I am getting metric request error while connecting to Azure Data Explorer cluster. The App ID and Key is correct and I suspect the length of the cluster URL may be an issue. The URL I am using is 52 characters long.

**Comment by aykutoezdogan** [comment]
@ManojRaheja 
could you please check if grafana-server is already running? I had the same issue and the solution was that grafana was already running.
Our URL also over 52, so I think you should give it a try.

**Comment by srclosson** [comment]
@ManojRaheja : A screenshot showing the error would also be helpful as well

**Comment by srclosson** [comment]
Impacting a paying customer. Looking to get this into the next sprint.

**Comment by srclosson** [comment]
Duplicate of #63
