### ISSUE TITLE
Cannot display traces using the plugin

### ISSUE THREAD

**Issue by vidommet** [grafana/azure-data-explorer-datasource#551]
**What happened**:
We upload our traces to Azure Data Explorer and are using the plugin to pull the data into Grafana. We are trying to display using the new [trace](https://grafana.com/docs/grafana/latest/explore/trace-integration/) support. We can map all the columns correctly as required but the tracing requires `frame.meta.preferredVisualisationType = 'trace'` which cannot be configured in the UI

**What you expected to happen**:
Allow traces as an option to be displayed.

**How to reproduce it (as minimally and precisely as possible)**:

Example trace creation from data explorer.

OTELTrace
| take 10
| project traceID = env_dt_traceId, spanID = env_dt_spanId, parentSpanID = parentId, serviceName =  env_name, serviceTags = "", startTime = PreciseTimeStamp, duration =  PreciseTimeStamp - startTime

**Screenshots**

**Anything else we need to know?**:

**Environment**:

- Grafana version: 9.3.2.2
- Plugin version: 4.1.10
- OS Grafana is installed on: Azure Managed Grafana
- User OS & Browser:
- Others:

**Comment by asimpson** [comment]
Hi! Tracing support is supported for the plugins listed on that page. We'll definitely take this as something to consider implementing in the future for ADX.

**Comment by AdallomRoy** [comment]
Is it because the plugin is missing something or because in Grafana you limit the visualization of traces for specific plugins?

**Comment by yarashagarwal** [comment]
This is a much needed feature!

**Comment by aangelisc** [comment]
Trace support was added in #594 😊
