### ISSUE TITLE
Configuration for On-Behalf-Of authentication via AzureSettings

### ISSUE THREAD

**Issue by kostrse** [grafana/azure-data-explorer-datasource#555]
On-Behalf-Of feature currently controlled by the `adxOnBehalfOf` feature toggle.

Since we are on the path for stabilization of the On-Behalf-Of feature and standard feature flags are not accessible from backend of external datasources, the proposal is to introduce a permanent option switch in the `azsettings.AzureSettings` structure.

OBO switch can be added into `[azure]` configuration section ([here](https://github.com/grafana/grafana/blob/c0865c863d55286e7c2d6ae25974254a240ccc5b/conf/sample.ini#L714)):
```ini
[azure]
managed_identity_enabled = true

# Enable/disable On-Behalf-Of authentication using AAD client configured in a datasource
client_obo_enabled = false
```
This configuration section parsed [here](https://github.com/grafana/grafana/blob/c0865c863d55286e7c2d6ae25974254a240ccc5b/pkg/setting/setting_azure.go#L5) into `azsettings.AzureSettings` structure.

We will need to extend the `azsettings.AzureSettings` in [github.com/grafana/grafana-azure-sdk-go/azsettings/settings.go](https://github.com/grafana/grafana-azure-sdk-go/blob/main/azsettings/settings.go) with additional boolean fiend and then update the [github.com/grafana/grafana-azure-sdk-go](https://github.com/grafana/grafana-azure-sdk-go) package in Grafana.

Related discussion: https://github.com/grafana/azure-data-explorer-datasource/issues/359#issuecomment-1136856614

**Comment by kostrse** [comment]
PR in Grafana Azure SDK:
- https://github.com/grafana/grafana-azure-sdk-go/pull/9

**Comment by asimpson** [comment]
Sorry for the delay @kostrse! I went ahead and approved 
- https://github.com/grafana/grafana-azure-sdk-go/pull/9
