### ISSUE TITLE
Default auth type is not present in json data

### ISSUE THREAD

**Issue by aangelisc** [grafana/azure-data-explorer-datasource#575]
The default auth type is not present in JSON data and does not get updated until `onChange` is called by either updating the auth type or editing credential information.

This affects the roll-out of user-based auth which will become the default authentication type. The json data should be appropriately created with the default auth type.

**Comment by kostrse** [comment]
<image src="https://github.com/grafana/azure-data-explorer-datasource/assets/1131253/85911a6f-6e15-43b0-a729-b5bb2d782d48" alt="Reload schema disabled" width="75%" />

**Comment by kostrse** [comment]
It's not easy to treat absence of any configuration as some default configuration.

Two reasons:
- defaults may change, so behavior of existing datasource will change too if it doesn't have explicit configuration.
- **most important**, for user identity auth,`oauthPassThru` should be explicitly set to work. So it makes impossible to have user identity as default configuration.

A solution would be to explicitly set some default configuration upon creation of the datasource.
