### ISSUE TITLE
Grafana doesnt display microsecond time series sometimes

### ISSUE THREAD

**Issue by Aswinsb** [grafana/azure-data-explorer-datasource#588]
I am using KQL to pull data from ADX to Grafana, in ADX it is showing up entire time (with microseconds) but grafana has some issues with display

ADX

[![ADX output][1]][1]

Grafana

[![Grafana][2]][2]

But if I zoom out a little it starts working

[![Grafana output][3]][3]

  [1]: https://i.stack.imgur.com/CeTwW.png
  [2]: https://i.stack.imgur.com/CdV2n.png
  [3]: https://i.stack.imgur.com/8fT5p.png

Anyone here knows how to fix this issue from grafana display side?

**Comment by aangelisc** [comment]
Hi @Aswinsb, do you just have to expand the table column size to display the full data?

**Comment by Aswinsb** [comment]
Hi @aangelisc, I wanred to know, why there is difference in values between ADX, grafana (1st and 3rd image)

**Comment by aangelisc** [comment]
I'm going to close this from lack of response, please let me know if this is still an issue!
