### ISSUE TITLE
Add k6 testing

### ISSUE THREAD

**Issue by bossinc** [grafana/azure-data-explorer-datasource#608]
Add k6 testing so we can compare k6 vs cypress.

clickhouse k6 testing example: https://github.com/grafana/clickhouse-datasource/pull/399 

More info from plugin platforms: https://raintank-corp.slack.com/archives/C01C4K8DETW/p1692371394593849

**Comment by asimpson** [comment]
While we're at it, it's probably worth it to also use [Playwright](https://playwright.dev/docs/api/class-playwright/) and add that to the testing matrix no?
