### ISSUE TITLE
Support for variable query which returns key/value pair?

### ISSUE THREAD

**Issue by erikbos** [grafana/azure-data-explorer-datasource#7]
Use Case: You may store metrics based on an 'ID' property but wish to have the template variable selection UI use a more human friendly label. e.g. You track metrics by domain with an internal domain ID but wish to use the domain's URL in the template variable selector UI.

There has been a generic Grafana issue https://github.com/grafana/grafana/issues/1032 open for years... 

It appears the MySQL data source has specific support for this, from https://grafana.com/docs/features/datasources/mysql/#query-variable :

> Another option is a query that can create a key/value variable. The query should return two columns that are named __text and __value. The __text column value should be unique (if it is not unique then the first value is used). The options in the dropdown will have a text and value that allows you to have a friendly name as text and an id as the value. 

Might be as simple as updating parseToVariables() to handle a two columns result set from the database?

**Comment by srclosson** [comment]
By default the template processor adds quotes to variables, and if the variable is using the 'multi-value' option, the template processor will expand each item selected and quote it. Example, if "one, two, three" were selected, the template process will return "'one', 'two', 'three'", which in the kusto language spec will return the static value for each iteration of data from the column (ie: if the query return 20 values, if will repeat 'one' 20 times.

There are a couple of options. Either use ${grafana_var:csv} to tell the template processor to use csv formatting that by default does not apply quotes on the expanded template (ie: "one, two, three").

The other option would be to update the plugin and specify the default formatting should be CSV.

I've not looked closely at the [kusto language spec](https://docs.microsoft.com/en-us/azure/kusto/query/re2) so there may be other use cases that may require special template processing which want to be taken into account.

Thoughts?

**Comment by erikbos** [comment]
Hi, this is not really about expanding the selection done in the UI to a particular query language syntax before it goes to the database.

It's more about the following use case, image two tables in a database:

1) table with customer details

| customer_id | customer_name |
| ------------- | ------------- |
| 3 | Dave Clark |
| 5 | Joe Eisner |

2) table with customer activity

| timestamp | customer_id | activity |
| ------------- | ------------- | ------------- |
| 2015-1-1 09:11 | 5 | arrived |
| 2015-1-1 09:13 | 3 | arrived |
| 2015-1-1 09:51 | 5 | departed |
| 2015-1-1 10:29 | 5 | arrived |
| 2015-1-1 13:44 | 5 | departed |

And you want to show the activities of just customer 'Dave' on a dashboard, customer to be selected in the UI. 

In Grafana you probably create a
- UI variable based upon db query, to select the customer by name
- a visualisation that plots customers activity based upon selected customer name

The challenge here is to carry the customer_id from UI variable to query in a panel. By default the variable text you see it is literally the same value that gets put in db query when the varialble is expanded. 

In the above scenario that would mean something like "SELECT * FROM activity where customer_id='Dave Clark'" but that won't work as that activity table does not have a column containing the customer's full name. 

To make this work the UI should show the name 'dave' while when expending the variable the value '3' should be inserted. The MySQL plugin as specific functionality for this use case

> Another option is a query that can create a key/value variable. The query should return two columns that are named __text and __value. The __text column value should be unique (if it is not unique then the first value is used). The options in the dropdown will have a text and value that allows you to have a friendly name as text and an id as the value.

For reference the MySQL datasource implementation for this is in parseMetricFindQueryResult() see: https://github.com/grafana/grafana/blob/66f6e16916fa1813e30c2ddd271acaf511cee560/public/app/plugins/datasource/mysql/response_parser.ts#L40

MySQL's parseMetricFindQueryResult checks for an optional two column result set from the database, if that's present it will that for separate values of the text and its value.

The corresponding ADX plugin's function is https://github.com/grafana/azure-data-explorer-datasource/blob/master/src/response_parser.ts#L173 

To make this work for ADX similar logic should be added there I think. (I am not familiar with Typescript)

Let me know if this clarifies it!

**Comment by srclosson** [comment]
Yes, this was very helpful Erik. Thank-you!

I'm coding this up now, but it would be very helpful if there was a datasource I could test against that shows the use case so I can properly test against it.

In the meantime, one more idea?
What about something like:

`customer_details |  summarize by strcat(customer_id, ': ', customer_name)`

in your template. You would then have '3: Dave Clark' and '5: Kevin Eisner' in your template variable. (Use select multi)

Then in your actual query do something like
`
customer_activity
| join kind = leftouter (customer_details) on $left.customer_id == $right.customer_id
| summarize $right.activity
| where strcat($left.customer_id, ':', $left.customer_name) matches regex "${template_var:regex}"
`

While I still intend to code the enhancement, does this satisfy the immediate use case?

**Comment by erikbos** [comment]
Hi, thanks for having a look at this one!  Something like the above can work, the (real) challenge is to do this in a maintainable way.


Our actual use case is actually way more complex, it's like four to five variables like:

`<company> <contract> <product> <sub product>`

- company comes from table Company
- contract comes from table Contract filtered by $company
- product comes from table Product filtered by $contract
- subproduct comes from table Subproduct filtered by $product

And all panels get their data from different database tables based on where customer usage is logged based on $subproduct. 

Now image 30 dashboards and the whole thing has become quite unmaintainable..

**Comment by erikbos** [comment]
A way to test this is by defining a variable "customer_id" with query:

> let customers = datatable(customer_name:string, customer_id:long, active:bool)
> [
>     'customer 1', 1, true,
>     'customer 2', 2, false,
>     'customer 3', 3, true,
> ];
> customers 
> | extend customer_label = strcat(customer_name, ' (', tostring(active), ')')
> | project __name = customer_label, __value = customer_id

and create a Table panel on the same dashboard with query
> print ("[[customer_id]]")

That should confirm whether it works or not I think.

**Comment by srclosson** [comment]
Hi @erikbos,

The update is complete, would you please confirm that the change satisfies your use case? You use it exactly like the mysql plugin
`
StormEvents | project __value = EventId, __text = EventType
`

Let me know

**Comment by erikbos** [comment]
I already gave it a quick try and it appears to work, great 👍👍 Will do a more thorough test tomorrow. Thanks for fixing this one!

**Comment by erikbos** [comment]
Tested a few more cases, works as expected! Thx

**Comment by micgruber** [comment]
> A way to test this is by defining a variable "customer_id" with query:
> 
> > let customers = datatable(customer_name:string, customer_id:long, active:bool)
> > [
> > 'customer 1', 1, true,
> > 'customer 2', 2, false,
> > 'customer 3', 3, true,
> > ];
> > customers
> > | extend customer_label = strcat(customer_name, ' (', tostring(active), ')')
> > | project __text = customer_label, __value = customer_id
> 
> and create a Table visualisation with "Table transform: Table" on the same dashboard with query
> 
> > print ("[[customer_id]]")
> 
> The output of the print will confirm whether $customer_id was set correctly or not.

I tried your query and reference the variable with: print("${query0:value}") but was not able to get the value just the key. I'm doing something wrong? print ("[[customer_id]]") did't worked for me.

![image](https://user-images.githubusercontent.com/19686895/196387697-86cc3a18-ae8d-40a5-b003-70693a6d1a8a.png)

![image](https://user-images.githubusercontent.com/19686895/196387965-eeb40f0d-5923-4cbb-be0b-58d41334ee7d.png)

**Comment by kosgdk** [comment]
@micgruber Just use `text` and `value` column names (without `__` prefix)
https://github.com/grafana/azure-data-explorer-datasource/issues/591
