### ISSUE TITLE
revisit monaco loading and webpack

### ISSUE THREAD

**Issue by briangann** [grafana/azure-data-explorer-datasource#71]
when using this loading method:

```
    (window as any).monaco = import(/* webpackChunkName: "/monaco.min" */ '../libs/monaco.min.js').then(() => {
```

webpack/babel is modifying the monaco.min.js file, and the editor can't be loaded.

when using this method (which is what I have reverted to using)
```
    (window as any).System.import(`/${scope.pluginBaseUrl}/libs/monaco.min.js`).then(() => {
```

the libs directory/content is copied to dist by toolkit unchanged, and the editor loads fine.

**Comment by joshhunt** [comment]
Just going to close this one in favor of #224
