### ISSUE TITLE
tooltip is displaying [Object Object] for some queries

### ISSUE THREAD

**Issue by briangann** [grafana/azure-data-explorer-datasource#73]
Create new dashboard, set data source to Kusto, choose Format as ADX Time Series, set time picker to Last 12 hours, and try this query:

```
print id='abc', Timestamp=range(bin(now(), 1h)-11h, bin(now(), 1h), 1h), y=dynamic([2,5,6,8,11,15,17,18,25,26,30,30])
```

![image](https://user-images.githubusercontent.com/7364245/74944075-0e2c5e80-53bb-11ea-9b96-ac99601c0157.png)

![image](https://user-images.githubusercontent.com/7364245/74944101-1a182080-53bb-11ea-8681-6691917171f3.png)

**Comment by joshhunt** [comment]
This was fixed 😌
