### ISSUE TITLE
Can't See The Databases In Network Tab In Grafana

### ISSUE THREAD

**Issue by k-ebanks** [grafana/azure-data-explorer-datasource#746]
**What happened**:

I am using this plugin to try to access data from a database in a cluster. I have permissions to query the target database and can do so on Azure Data Explorer. 
When in the explorer page, I took a look at the network tab in developer tools and a response comes back under the name "databases" and the database that I want to query is present in that response. However, on the UI there is no way for me to select my database, all of the dropdowns say "No options found". In addition to this, I see this prompt in a yellow box "Table schema loaded successfully but without any columns".

**What you expected to happen**:
I should be able to at least see my database as an option. So that I can query it. If I can't see it then an explanation of why not would be helpful.

**Screenshots**
Me setting up the plugin/auth correctly
<img width="959" alt="image" src="https://github.com/grafana/azure-data-explorer-datasource/assets/46906036/b736b4f4-1a55-4421-b943-ef02c9089c74">

Problem faced when trying to access any databases on the cluster. See the service responses on the right.
<img width="960" alt="image" src="https://github.com/grafana/azure-data-explorer-datasource/assets/46906036/b14f89f0-b0ec-43fd-985a-8dde777a7cee">

**Environment**:

- Grafana version: Grafana Cloud 10.2.1
- Plugin version: 4.7.0
- User OS & Browser: Windows + Edge Browser

**Comment by bossinc** [comment]
I believe the formatting of your cluster URL is incorrect. It should be `https://<cluster-name>.<region>.kusto.windows.net`

**Comment by k-ebanks** [comment]
Thank you for getting back to me,

The URL I used (`kusto.aria.microsoft.com`) is the only one that has been used by my team so far. I've asked around to see whether we have another URL of the form `https://<cluster-name>.<region>.kusto.windows.net` and it doesn't seem like we do. 

We are migrating our dashboards from Jarvis and where same URL was used and we were able to query the database successfully. Additionally, I'm accessing a test cluster and our target cluster on Kusto Explorer, my test cluster has a 'Data Source' URL in the format that you request and my target cluster doesn't.

<img width="997" alt="image" src="https://github.com/grafana/azure-data-explorer-datasource/assets/46906036/60caba04-2590-4ed3-9334-7e72c9c2a46b">

I think that the URL (`kusto.aria.microsoft.com`) is correct but do you only accept URLs in the format `https://<cluster-name>.<region>.kusto.windows.net`?

I don't think I'll be able to authenticate in another way right now as I'm not the cluster owner so won't be able to set it up.

**Comment by k-ebanks** [comment]
Update again: I have managed to get it working after updating the URL and tweaking the additional settings panel. Feel free to close this issue, thank you! :smile:

**Comment by rahulrana-XOM** [comment]
Hi, I am seeing the same "Table schema loaded successfully but without any columns" any tips?

I have an Event Hub streaming into an ADX instance and my data source in Grafana is set up to read from it. I see all of the data in my ADX database so not sure...

**Comment by aangelisc** [comment]
Hi @rahulrana-XOM, are you able to open a separate issue please. You may not have the appropriate permissions to view the data in ADX.

Thank you @k-ebanks, I'm glad your issue was resolved 😊

**Comment by maglims** [comment]
@k-ebanks , I have the exact issue here. My grafana service is not able to make a connection to https://kusto.aria.microsoft.com/.

Could you please share the connection you have used to make this work? Thank you!
