### ISSUE TITLE
Errors running in Kubernetes behind NGINX ingress 

### ISSUE THREAD

**Issue by joemillerr** [grafana/azure-data-explorer-datasource#76]
I get the following error in Grafana when running behind an NGINX ingress in Kubernetes.  This causes the query editor to not appear.

```
GET https://myhost.domain.com/public/plugins/grafana-azure-data-explorer-datasource/libs/monaco.min.js?_cache=1582591324973 
net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK) 
tti-polyfill.js:4 
```

I've tried several different versions and combinations of Grafana and the plugin with the same results.  I've tried adjusting various nginx proxy buffer settings to no avail.  That path does exist and is accessible.  The logs for both Grafana and NGINX have nothing useful in them.  It does not repro in Docker or on a VM so my hunch was the reverse proxy but none of the usual suspects appear to be having any effect.  I see a few similar issues so I figured I would post here.  I'm using the stable Grafana Helm chart.

Grafana 6.6.1
Plugin version 2.0.4

**Comment by joemillerr** [comment]
It's worth noting this is just one of many plugins and datasources we use and it is the only one having any issues.  I've also tried several different adjustments to the root_url to see if that is what is wrong (even though the URL that fails is valid) but it doesn't seem to have any effect on the URL.

**Comment by c-r-i-s** [comment]
@joemillerr have you solved this issue? I am having very similar errors on my setup (kubernetes, nginx based) and any updates on this would greatly appreciated. 
Thanks!

**Comment by joemillerr** [comment]
This actually had to do with the fact that I run my ingress behind a SSL terminating load balancer.  If you are in a similar situation I would recommend adding your certificate to the ingress.

**Comment by c-r-i-s** [comment]
Thanks @joemillerr . I will dig into this with my IT colleagues and hopefully solve this issue as well. I believe we have a similar issue on our side, and your input may help us to solve this.
