### ISSUE TITLE
Query editor breaks if grafana has root_url set

### ISSUE THREAD

**Issue by blackbaud-brandonstirnaman** [grafana/azure-data-explorer-datasource#8]
When deployed behind a proxy, most configurations set `root_url` in grafana.ini configuration. For my configuration, that looks like this:

```
server:
  root_url: "%(protocol)s://%(domain)s/proxy/grafana/"
```

In this setup, the data source loads correctly (can test connection, choose database, etc) but the query editor breaks trying to load up Monaco.

https://github.com/grafana/azure-data-explorer-datasource/blob/080f104a024e1be6b257ed1004907faab095c15a/src/monaco/kusto_monaco_editor.ts#L12

In our scenario it looks like `pluginBaseUrl` above is set to `public/plugins/grafana-azure-data-explorer-datasource` when it should be set to `proxy/grafana/public/plugins/grafana-azure-data-explorer-datasource` (which includes the subpath from the root_url entry).

**Comment by daniellee** [comment]
This is a bug - will get it out in a release this week probably.

**Comment by blackbaud-brandonstirnaman** [comment]
Any updates on this?

**Comment by briangann** [comment]
fixed in current release

**Comment by c-r-i-s** [comment]
I ended up facing again this issue recently (currently using with 6.7.2 grafana). Any hints where to focus to try to nail our issue down?  @briangann  any suggestions? How was this originally fixed back to 2019?
