### ISSUE TITLE
Data source settings page missing details

### ISSUE THREAD

**Issue by zingaroo** [grafana/azure-data-explorer-datasource#85]
When adding an ADX data source there is no details section in the settings page as the documentation shows. Version 6.2.5 (commit: 6082d19).

![ADX datasource no details](https://user-images.githubusercontent.com/27195985/79762567-34bb3700-8323-11ea-81da-5d1c4ec0af7c.png)

**Comment by sunker** [comment]
Don't know when this was fixed, but it works fine in v3.3.1.
