### ISSUE TITLE
Allow switching datasource with variable

### ISSUE THREAD

**Issue by rockynox** [grafana/azure-data-explorer-datasource#86]
I've tried to implement an environment switcher in order to switch between my different environment.
![image](https://user-images.githubusercontent.com/8975235/80602514-85bbe100-8a2f-11ea-9f47-ab30f458a080.png)

The thing is, my databases have different names between environment. So if I set the query data source on "$Environment" :

![image](https://user-images.githubusercontent.com/8975235/80602826-e5b28780-8a2f-11ea-81e8-53c06dfa0507.png)

it will work the first time (as the plugin will find the database in the datasource) but as soon as I change the environment, it will keep searching for the same database name in this other environment -spoiler it doesn't exist- and I have the error: 

> Entity ID 'My-First-Env_databaseName' of kind 'Database' was not found.

I don't know if I miss something in the configuration, but it looks like it's not possible to do this today.

Thanks for your answer.

**Comment by daniellee** [comment]
To switch between data sources, you can use a template variable of type datasource.

**Comment by rockynox** [comment]
It's what I did, but as soon as my database name's are different between my datasource, I do not work when I change my variable value.

![image](https://user-images.githubusercontent.com/8975235/88548555-8f011d80-d01f-11ea-8e88-fad8cb97d5b2.png)

**Comment by rockynox** [comment]
It seems that the database name are loaded only after selected the datasource in the edit mode. 

For example if I set up a graph with datasource = $env, then during the query edition, i'll have to select a database (let's say "database 1") corresponding to the current env selected. ("dataSource 1")
Then, I save my graph, and I change my datasource variable to "dataSource 2". In that case it would result on an 400 error because the graph keep trying to query "database 1" on "dataSource 2".

I hope it's clearer.

**Comment by rockynox** [comment]
For the record, I managed to do it by using the database() function.

1. Create another variable: 
![image](https://user-images.githubusercontent.com/8975235/100088024-d96c9c80-2e4f-11eb-845c-3ee1704e0e34.png)

2. When doing your query, use this variable for the database field and the datasource variable for the datasource selector:
![image](https://user-images.githubusercontent.com/8975235/100088296-336d6200-2e50-11eb-83bf-20722d7926a9.png)
