### ISSUE TITLE
Plugin does not load on Grafana 7 since it is unsigned

### ISSUE THREAD

**Issue by gilkgit** [grafana/azure-data-explorer-datasource#87]
Plugin does not load by default on Grafana 7 since it is unsigned (Tested with latest version of the plugin 2.0.5 and latest version of Grafana).

I manually approved it in my config but it might be worth properly signing it.

**Comment by briangann** [comment]
new release pending, will be signed and v7 verified.

**Comment by gregrems** [comment]
Hi Brian. 
First thank you on releasing updated plugin, works like magic. :-)

My question is regarding the plugin signature and manifest. 
I get yours source code and I use some manipulation on query before forward it to ADX.
I would like to know how I can make it signed when compiling. 
As I'm getting an error: 
-----------------------------------------------------
[36mDBUG[0m[07-06|06:57:55] Getting signature state of plugin        [36mlogger[0m=plugins [36mplugin[0m=grafana-azure-data-explorer-datasource
[36mDBUG[0m[07-06|06:57:55] Verifying contents of plugin manifest    [36mlogger[0m=plugins [36mplugin[0m=grafana-azure-data-explorer-datasource
[33mWARN[0m[07-06|06:57:55] Plugin file's signature has been modified versus manifest [33mlogger[0m=plugins [33mplugin[0m=grafana-azure-data-explorer-datasource [33mfilename[0m="C:<\\Program Files\\Grafana\\data\\plugins\\grafana-azure-data-explorer-datasource/grafana-azure-data-explorer-datasource_windows_amd64.exe>"
-----------------------------------------------------

At this point what is helped me is, Grafana version 7 feature, of allow_loading_unsigned_plugins.
Let me know if any additional information is required. 

Thank you once again.
Grigori.

**Comment by gregrems** [comment]
@briangann,
Any update?

**Comment by gregrems** [comment]
@briangann 
Hi Brian, 
Is there any way to signed the plugin?
Can you describe how you had created it signed?

**Comment by mckn** [comment]
This one should be fixed in 3.x versions.
