### ISSUE TITLE
On the query editor, the "Help" section is always opened by default, can you change it to closed by default?

### ISSUE THREAD

**Issue by gilkgit** [grafana/azure-data-explorer-datasource#88]
On the query editor, the "Help" section is always opened by default every time I enter the editor.
I need to collapse it all the time. it's impossible to see the "Raw Query" results (because I need to scroll the really long "Help" section (all the time).
If I use two queries in the query editor, then each one has its own help.

**Comment by christineywang** [comment]
+1 from Microsoft.

**Comment by mckn** [comment]
This is fixed in the v3.x
