### ISSUE TITLE
Support for multiple metrics in Time Series query resultset?

### ISSUE THREAD

**Issue by erikbos** [grafana/azure-data-explorer-datasource#9]
The plugin appears to support one metric per query only:
> Time Series queries are for the Graph Panel (and other panels like the Single Stat panel) and must contain a datetime column, a metric name column and a value column.

It would be great if the time series query function would support multiple metric columns.

Imagine a visualisation thats shows the number of HTTP status codes 200,300,400, 500 of a webserver access log over time. I can generate the result dataset with one Kusto query. But I cannot use that query in this data source at the moment. 

Example result set:

<img width="543" alt="Screenshot 2019-05-02 at 17 20 40" src="https://user-images.githubusercontent.com/1421163/57086845-326d6080-6cff-11e9-895d-3b70b90b51dd.png">

To create the whole visualisation I need to add a separate Timeseries configuration for each http status code to be rendered, each with a separate Kusto query to produce the metric result set for that http status code.

This results in:
- additional and unnecessary database load (I've got a dataset with billions of rows)
- lower response time to get the Grafana page loaded
- duplicate configuration

Most other data sources appear to support multiple metrics in the result set, e.g.:

MySQL datasource supports multiple column:
<img width="699" alt="Screenshot 2019-04-30 at 22 19 07" src="https://user-images.githubusercontent.com/1421163/56990690-0bdfe600-6b96-11e9-81d0-c175423396b9.png">

PostgresSQL datasource supports multiple metric columns:
<img width="726" alt="Screenshot 2019-04-30 at 22 19 52" src="https://user-images.githubusercontent.com/1421163/56990713-1b5f2f00-6b96-11e9-8bbe-b36a4db6d7fa.png">

**Comment by daniellee** [comment]
I'm not sure I understand this issue. This looks like a table with multiple columns. It is possible (and always has been) to have multiple columns in a response if it is table data. You just have to select Format as Table in the query editor.

Timeseries data is a very specific format with three fields: timestamp, metric name and value. It is not possible to have multiple values. The graph panel needs timeseries data for the graph visualization. Are you talking about the graph panel and this feature:

`You may add further value columns by clicking the plus button and selecting Column from the menu. Multiple value columns will be plotted as separate series in the graph panel.`

This is a more advanced and relatively new feature that only the SQL datasources support (so no other datasources support this as far as I know) but it would be possible to add to the Azure Data Explorer datasource.

**Comment by srclosson** [comment]
Once a couple of pull requests get merged in we ca re-release this plugin and this should be solved.

**Comment by srclosson** [comment]
https://grafana.com/grafana/plugins/grafana-azure-data-explorer-datasource

2.0 re-released and closing this issue.
