### ISSUE TITLE
Refreshing a Time Series does not preserve sort order used in the Kusto's query 

### ISSUE THREAD

**Issue by gilkgit** [grafana/azure-data-explorer-datasource#90]
When formatting as Time Series, upon query refresh, the plugin ignores the sort order used in the query.
This (at-least) breaks ordering in bar gauge, essentially, every refresh changes the order randomly.
I didn't find a workaround and sorting in bar-gauge is a "must" feature for me :(

Reproes both on Grafana 6.7 and on 7.
This is a regression since it worked fine on the V1.4 .

Repro:
query:

datatable (Value:int , name:string, Timestamp: datetime )
[1,"A",datetime(2020-05-20), 2,"B", datetime(2020-05-21) ,3,"C", datetime(2020-05-22)]
| order by Value desc  

Format as: Time series

Visualization: Bar Gauge

run the query (Most of the time the initial order is fine).
then wait for to auto refresh (set the refresh to 5 sec).

Result
Order changes randomly on each refresh.

**Comment by t-sean** [comment]
I think this is the same issue as mine posted at #42 

I was able to use your query with my custom code in that issue and the order persisted.

**Comment by gilkgit** [comment]
@t-sean thanks for sharing.
Say - do you get the labels for the chart in order after the fix?
for me they randomly change their order on every refresh making it impossible to work with busy charts:

![image](https://user-images.githubusercontent.com/55378597/83607716-60694800-a584-11ea-8b32-b5981bc0fbda.png)

**Comment by t-sean** [comment]
Yeah the label also doesn't change after refresh

![image](https://user-images.githubusercontent.com/17075206/83640519-3c086e00-a57a-11ea-815f-34ef29eb20a4.png)

**Comment by sunker** [comment]
I can't reproduce this. Think it was fixed recently in the [backend sdk](https://github.com/grafana/grafana-plugin-sdk-go). Feel free to re-open the issue if you're able to reproduce it.
