### ISSUE TITLE
When chaning root_url monaco can not be recived

### ISSUE THREAD

**Issue by Eossu** [grafana/azure-data-explorer-datasource#93]
When we change the configuration of grafana to a diffrent root path monaco can not be downloaded.

example:
[server]
root_url = https://%(domain)s/**monitor**

then we should recive monaco from: https://domain.com/monitor/public/plugins/grafana-azure-data-explorer-datasource/libs/monaco.min.js?_cache=#######

But its beeing tried to get from https://domain.com/public/plugins/grafana-azure-data-explorer-datasource/libs/monaco.min.js?_cache=#####

**Comment by joshhunt** [comment]
Closing this in favor of https://github.com/grafana/azure-data-explorer-datasource/issues/203
