### ISSUE TITLE
Collapsed query row for new visualizations

### ISSUE THREAD

**Issue by SteffiHerbst** [grafana/azure-data-explorer-datasource#940]
**What happened**:

Query row is always collapsed when creating new visualization, drop down menus for "Cluster", "Database" and "Format as" are shown.
Although button tooltip indicates it should be expanded: tooltip shows "Collapse query row".

**What you expected to happen**:

Query row (builder / text box) should be shown by default without the need to click twice on the collapse-button.

**How to reproduce it (as minimally and precisely as possible)**:

1. Select ADX data source as default
2. Create new dashboard
3. Add new visualization 
4. Query row is collapsed, only drop down menus for "Cluster", "Database" and "Format as" are shown.
5. User needs to click on button with tooltip "Collapse query row" to collapse it completely and once more to expand it whereas query row gets visible finally

**Environment**:

- Grafana version: Azure Managed Grafana v10.4.3 (6e6fbf6a34)
- Plugin version: 5.0.3
- User OS & Browser: Windows, Chrome

**Comment by alyssabull** [comment]
Hi @SteffiHerbst - thanks for reporting this issue. I have been able to fix it with [this PR](https://github.com/grafana/azure-data-explorer-datasource/pull/1001).
