### ISSUE TITLE
After 7.0, Cell Values for Hidden Fields Not Supported

### ISSUE THREAD

**Issue by christineywang** [grafana/azure-data-explorer-datasource#96]
An existing customer previously was able to use hidden fields for table cell link variables in 6.x:
<img width="1037" alt="Screen Shot 2020-07-13 at 1 55 57 PM" src="https://user-images.githubusercontent.com/19804181/87365375-e933b600-c52a-11ea-838c-684b8665abd6.png">

<br>

Now, in 7.x, he is not able to hide a table field (using transformations) and still retain the value of the hidden field for a table cell link:

<img width="1040" alt="Screen Shot 2020-07-13 at 2 04 59 PM" src="https://user-images.githubusercontent.com/19804181/87365485-3748b980-c52b-11ea-9556-bf1fc152480e.png">

This community [comment](https://community.grafana.com/t/using-links-in-tables/4651/12) appears to be related.

The interesting thing is for panels that existed in his 6.x version, they got ported over to the updated version correctly. But he is not able to create _**new**_ panels with hidden table cell variables.

Is there a workaround for this for which we are not aware? Thank you!

**Comment by vickyyyyyyy** [comment]
think I can reproduce this with Grafana v8.2.5 and ADX version 3.6.0

When the `ActivityName` field is not hidden, it comes up:

![Screenshot 2021-11-22 at 13 53 37](https://user-images.githubusercontent.com/36230812/142873681-c9284cca-5a2e-4593-b8f6-0662a4f910f7.png)

When the `ActivityName` field is hidden, it doesn't come up:

![Screenshot 2021-11-22 at 13 53 48](https://user-images.githubusercontent.com/36230812/142873691-c1db1204-269e-4718-83ef-f1bc8166a2de.png)

**Comment by Grrrolf** [comment]
This is/was a Grafana issue and not a data source issue. See this [issue](https://github.com/grafana/grafana/issues/24092).
Use the 'hide in table' override: 
<img width="397" alt="image" src="https://user-images.githubusercontent.com/10052794/153738897-e2d74259-9079-4517-8f6a-c73716bd1af5.png">
Which let you choose the value you have hidden.
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/10052794/153738964-7be56ee9-d6d4-4b20-b44c-b591c989f696.png">
This only works when the column is hidden using an override. When hidden using the organize fields transformation, it will not work.

**Comment by yaelleC** [comment]
Thanks very much @Grrrolf .
Closing this issue as using the `hide in table` override is indeed the way to go in this case.

**Comment by dannotes** [comment]
Version 10.2.0, Hide in table is not showing in 'Bar Gauge' also I cannot use the hidden column in data links. Any suggestions?
