### ISSUE TITLE
Setting reporting_enabled or check_for_updates to false causes report of needing to update to 5.3.0 or later when running 7.x

### ISSUE THREAD

**Issue by cschertz** [grafana/azure-data-explorer-datasource#97]
Setting reporting_enabled or check_for_updates to false causes report of needing to update to 5.3.0 or later when running 7.x.   When either is set to false a version warning is displayed. 

This image shows the update message that shows when either set to false 
![GitHubADXPluginIssue](https://user-images.githubusercontent.com/799428/87722802-bdad0780-c786-11ea-87f6-7c07ff9968af.jpg)

When both  reporting_enabled or check_for_updates are set to true
This image shows that the warning is gone
![GoodAdx](https://user-images.githubusercontent.com/799428/87725298-05359280-c78b-11ea-81fa-abfe25026243.PNG)

This may seem basic but it causes support requests to flow to our team and that cost adds up. 

Any help would be greatly appreciated. 

Also are the any instructions on how to build and debug this project.   I would love to fix this problem and add a couple of features but have no clue how to get started.

**Comment by sunker** [comment]
@cschertz do you still have this problem?

**Comment by cschertzmsft** [comment]
We still see the needs upgrade notification

**Comment by vickyyyyyyy** [comment]
thanks for reporting! @cschertz we can't seem to replicate this with Grafana v8.2.5 and ADX v3.6.0 - can you let us know if this is still a problem and if so, which versions you are seeing this with?

**Comment by sunker** [comment]
We've closed this issue since it needs more information and hasn't had any activity recently. We can re-open it after you you add more information. To avoid having your issue closed in the future, please read our [CONTRIBUTING](https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md) guidelines.

Happy graphing!
