### ISSUE TITLE
plugin failed: Loading plugins/grafana-azure-data-explorer-datasource/module

### ISSUE THREAD

**Issue by liuhename** [grafana/azure-data-explorer-datasource#98]
I have a grafana server version 5.3.4

i used grafana-cli command to install the plugin version 2.0.5. The plugin has been install successfully. but there is a issue when i add the datasource from grafana's web console interface:

the error log appears on the web console :

 plugin failed
Error: Fetch error: 404 Not Found Instantiating http://172.30.2.88:3000/public/@grafana/data Loading http://172.30.2.88:3000/public/plugins/grafana-azure-data-explorer-datasource/module.js Loading plugins/grafana-azure-data-explorer-datasource/module

I also try to use the plugin version 2.0.4 2.0.3. 2.0.2. they faced the same issue.

Could you help to have a look ?

I use the same way install the plugin on grafana server version 6.4.3. It works well.

**Comment by bozturkMSFT** [comment]
I am having a similar issue. I created a Grafana Azure Resource under my azure subscription. When I go to Configuration->Settings page, at the bottom, I can see that the Grafana version is "**Grafana v6.2.5 (commit: 6082d19)**".

When I try to add an Azure Data Explorer data source, I get to this screen: 
![image](https://user-images.githubusercontent.com/60651445/87953900-ed704e00-caab-11ea-84e4-8f4a84e16aab.png)

Clicking on "Save & Test" displays the following error on the top-right corner of the screen:
`Error: Fetch error: 404 Not Found Instantiating http://<app name>.eastus2.cloudapp.azure.com:3000/public/@grafana/data Loading http://<app name>.eastus2.cloudapp.azure.com:3000/public/plugins/grafana-azure-data-explorer-datasource/module.js Loading plugins/grafana-azure-data-explorer-datasource/module`

When I go to "configuration -> plugins" on the left menu and click on Azure Data Explorer Data Source, loading animation appears but the content never loads:
![image](https://user-images.githubusercontent.com/60651445/87954317-7edfc000-caac-11ea-98b4-0eeec265a88b.png)

**Comment by bozturkMSFT** [comment]
I updated grafana to v7.1.0 (8101355285) and reinstalled the plugin. Now I can configure the data source. Clicking on "Save & Test" shows a brief "Datasource updated" message and then an error: "Metric request error".

**Comment by sunker** [comment]
@liuhename - grafana version 5.x doesn't have support for the ADX datasource. Please upgrade to 7.1.x and it should work.
